# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient

from ._private.schemas import GUARD_DUTY_API_SERVICE as _SCHEMA_GUARD_DUTY_API_SERVICE
from .auth import HTTPAuthSchemeResolver
from .models import (
    AcceptAdministratorInvitationInput,
    AcceptAdministratorInvitationOutput,
    AcceptInvitationInput,
    AcceptInvitationOutput,
    ArchiveFindingsInput,
    ArchiveFindingsOutput,
    CreateDetectorInput,
    CreateDetectorOutput,
    CreateFilterInput,
    CreateFilterOutput,
    CreateIPSetInput,
    CreateIPSetOutput,
    CreateInvestigationInput,
    CreateInvestigationOutput,
    CreateMalwareProtectionPlanInput,
    CreateMalwareProtectionPlanOutput,
    CreateMembersInput,
    CreateMembersOutput,
    CreatePublishingDestinationInput,
    CreatePublishingDestinationOutput,
    CreateSampleFindingsInput,
    CreateSampleFindingsOutput,
    CreateThreatEntitySetInput,
    CreateThreatEntitySetOutput,
    CreateThreatIntelSetInput,
    CreateThreatIntelSetOutput,
    CreateTrustedEntitySetInput,
    CreateTrustedEntitySetOutput,
    DeclineInvitationsInput,
    DeclineInvitationsOutput,
    DeleteDetectorInput,
    DeleteDetectorOutput,
    DeleteFilterInput,
    DeleteFilterOutput,
    DeleteIPSetInput,
    DeleteIPSetOutput,
    DeleteInvitationsInput,
    DeleteInvitationsOutput,
    DeleteMalwareProtectionPlanInput,
    DeleteMalwareProtectionPlanOutput,
    DeleteMembersInput,
    DeleteMembersOutput,
    DeletePublishingDestinationInput,
    DeletePublishingDestinationOutput,
    DeleteThreatEntitySetInput,
    DeleteThreatEntitySetOutput,
    DeleteThreatIntelSetInput,
    DeleteThreatIntelSetOutput,
    DeleteTrustedEntitySetInput,
    DeleteTrustedEntitySetOutput,
    DescribeMalwareScansInput,
    DescribeMalwareScansOutput,
    DescribeOrganizationConfigurationInput,
    DescribeOrganizationConfigurationOutput,
    DescribePublishingDestinationInput,
    DescribePublishingDestinationOutput,
    DisableOrganizationAdminAccountInput,
    DisableOrganizationAdminAccountOutput,
    DisassociateFromAdministratorAccountInput,
    DisassociateFromAdministratorAccountOutput,
    DisassociateFromMasterAccountInput,
    DisassociateFromMasterAccountOutput,
    DisassociateMembersInput,
    DisassociateMembersOutput,
    EnableOrganizationAdminAccountInput,
    EnableOrganizationAdminAccountOutput,
    GetAdministratorAccountInput,
    GetAdministratorAccountOutput,
    GetCoverageStatisticsInput,
    GetCoverageStatisticsOutput,
    GetDetectorInput,
    GetDetectorOutput,
    GetFilterInput,
    GetFilterOutput,
    GetFindingsInput,
    GetFindingsOutput,
    GetFindingsStatisticsInput,
    GetFindingsStatisticsOutput,
    GetIPSetInput,
    GetIPSetOutput,
    GetInvestigationInput,
    GetInvestigationOutput,
    GetInvitationsCountInput,
    GetInvitationsCountOutput,
    GetMalwareProtectionPlanInput,
    GetMalwareProtectionPlanOutput,
    GetMalwareScanInput,
    GetMalwareScanOutput,
    GetMalwareScanSettingsInput,
    GetMalwareScanSettingsOutput,
    GetMasterAccountInput,
    GetMasterAccountOutput,
    GetMemberDetectorsInput,
    GetMemberDetectorsOutput,
    GetMembersInput,
    GetMembersOutput,
    GetOrganizationStatisticsInput,
    GetOrganizationStatisticsOutput,
    GetRemainingFreeTrialDaysInput,
    GetRemainingFreeTrialDaysOutput,
    GetThreatEntitySetInput,
    GetThreatEntitySetOutput,
    GetThreatIntelSetInput,
    GetThreatIntelSetOutput,
    GetTrustedEntitySetInput,
    GetTrustedEntitySetOutput,
    GetUsageStatisticsInput,
    GetUsageStatisticsOutput,
    InviteMembersInput,
    InviteMembersOutput,
    ListCoverageInput,
    ListCoverageOutput,
    ListDetectorsInput,
    ListDetectorsOutput,
    ListFiltersInput,
    ListFiltersOutput,
    ListFindingsInput,
    ListFindingsOutput,
    ListIPSetsInput,
    ListIPSetsOutput,
    ListInvestigationsInput,
    ListInvestigationsOutput,
    ListInvitationsInput,
    ListInvitationsOutput,
    ListMalwareProtectionPlansInput,
    ListMalwareProtectionPlansOutput,
    ListMalwareScansInput,
    ListMalwareScansOutput,
    ListMembersInput,
    ListMembersOutput,
    ListOrganizationAdminAccountsInput,
    ListOrganizationAdminAccountsOutput,
    ListPublishingDestinationsInput,
    ListPublishingDestinationsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    ListThreatEntitySetsInput,
    ListThreatEntitySetsOutput,
    ListThreatIntelSetsInput,
    ListThreatIntelSetsOutput,
    ListTrustedEntitySetsInput,
    ListTrustedEntitySetsOutput,
    SendObjectMalwareScanInput,
    SendObjectMalwareScanOutput,
    StartMalwareScanInput,
    StartMalwareScanOutput,
    StartMonitoringMembersInput,
    StartMonitoringMembersOutput,
    StopMonitoringMembersInput,
    StopMonitoringMembersOutput,
    TagResourceInput,
    TagResourceOutput,
    UnarchiveFindingsInput,
    UnarchiveFindingsOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateDetectorInput,
    UpdateDetectorOutput,
    UpdateFilterInput,
    UpdateFilterOutput,
    UpdateFindingsFeedbackInput,
    UpdateFindingsFeedbackOutput,
    UpdateIPSetInput,
    UpdateIPSetOutput,
    UpdateMalwareProtectionPlanInput,
    UpdateMalwareProtectionPlanOutput,
    UpdateMalwareScanSettingsInput,
    UpdateMalwareScanSettingsOutput,
    UpdateMemberDetectorsInput,
    UpdateMemberDetectorsOutput,
    UpdateOrganizationConfigurationInput,
    UpdateOrganizationConfigurationOutput,
    UpdatePublishingDestinationInput,
    UpdatePublishingDestinationOutput,
    UpdateThreatEntitySetInput,
    UpdateThreatEntitySetOutput,
    UpdateThreatIntelSetInput,
    UpdateThreatIntelSetOutput,
    UpdateTrustedEntitySetInput,
    UpdateTrustedEntitySetOutput,
)


_ServiceInterceptor = Union[
    Interceptor[
        AcceptAdministratorInvitationInput,
        AcceptAdministratorInvitationOutput,
        Any,
        Any,
    ],
    Interceptor[AcceptInvitationInput, AcceptInvitationOutput, Any, Any],
    Interceptor[ArchiveFindingsInput, ArchiveFindingsOutput, Any, Any],
    Interceptor[CreateDetectorInput, CreateDetectorOutput, Any, Any],
    Interceptor[CreateFilterInput, CreateFilterOutput, Any, Any],
    Interceptor[CreateInvestigationInput, CreateInvestigationOutput, Any, Any],
    Interceptor[CreateIPSetInput, CreateIPSetOutput, Any, Any],
    Interceptor[
        CreateMalwareProtectionPlanInput, CreateMalwareProtectionPlanOutput, Any, Any
    ],
    Interceptor[CreateMembersInput, CreateMembersOutput, Any, Any],
    Interceptor[
        CreatePublishingDestinationInput, CreatePublishingDestinationOutput, Any, Any
    ],
    Interceptor[CreateSampleFindingsInput, CreateSampleFindingsOutput, Any, Any],
    Interceptor[CreateThreatEntitySetInput, CreateThreatEntitySetOutput, Any, Any],
    Interceptor[CreateThreatIntelSetInput, CreateThreatIntelSetOutput, Any, Any],
    Interceptor[CreateTrustedEntitySetInput, CreateTrustedEntitySetOutput, Any, Any],
    Interceptor[DeclineInvitationsInput, DeclineInvitationsOutput, Any, Any],
    Interceptor[DeleteDetectorInput, DeleteDetectorOutput, Any, Any],
    Interceptor[DeleteFilterInput, DeleteFilterOutput, Any, Any],
    Interceptor[DeleteInvitationsInput, DeleteInvitationsOutput, Any, Any],
    Interceptor[DeleteIPSetInput, DeleteIPSetOutput, Any, Any],
    Interceptor[
        DeleteMalwareProtectionPlanInput, DeleteMalwareProtectionPlanOutput, Any, Any
    ],
    Interceptor[DeleteMembersInput, DeleteMembersOutput, Any, Any],
    Interceptor[
        DeletePublishingDestinationInput, DeletePublishingDestinationOutput, Any, Any
    ],
    Interceptor[DeleteThreatEntitySetInput, DeleteThreatEntitySetOutput, Any, Any],
    Interceptor[DeleteThreatIntelSetInput, DeleteThreatIntelSetOutput, Any, Any],
    Interceptor[DeleteTrustedEntitySetInput, DeleteTrustedEntitySetOutput, Any, Any],
    Interceptor[DescribeMalwareScansInput, DescribeMalwareScansOutput, Any, Any],
    Interceptor[
        DescribeOrganizationConfigurationInput,
        DescribeOrganizationConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        DescribePublishingDestinationInput,
        DescribePublishingDestinationOutput,
        Any,
        Any,
    ],
    Interceptor[
        DisableOrganizationAdminAccountInput,
        DisableOrganizationAdminAccountOutput,
        Any,
        Any,
    ],
    Interceptor[
        DisassociateFromAdministratorAccountInput,
        DisassociateFromAdministratorAccountOutput,
        Any,
        Any,
    ],
    Interceptor[
        DisassociateFromMasterAccountInput,
        DisassociateFromMasterAccountOutput,
        Any,
        Any,
    ],
    Interceptor[DisassociateMembersInput, DisassociateMembersOutput, Any, Any],
    Interceptor[
        EnableOrganizationAdminAccountInput,
        EnableOrganizationAdminAccountOutput,
        Any,
        Any,
    ],
    Interceptor[GetAdministratorAccountInput, GetAdministratorAccountOutput, Any, Any],
    Interceptor[GetCoverageStatisticsInput, GetCoverageStatisticsOutput, Any, Any],
    Interceptor[GetDetectorInput, GetDetectorOutput, Any, Any],
    Interceptor[GetFilterInput, GetFilterOutput, Any, Any],
    Interceptor[GetFindingsInput, GetFindingsOutput, Any, Any],
    Interceptor[GetFindingsStatisticsInput, GetFindingsStatisticsOutput, Any, Any],
    Interceptor[GetInvestigationInput, GetInvestigationOutput, Any, Any],
    Interceptor[GetInvitationsCountInput, GetInvitationsCountOutput, Any, Any],
    Interceptor[GetIPSetInput, GetIPSetOutput, Any, Any],
    Interceptor[
        GetMalwareProtectionPlanInput, GetMalwareProtectionPlanOutput, Any, Any
    ],
    Interceptor[GetMalwareScanInput, GetMalwareScanOutput, Any, Any],
    Interceptor[GetMalwareScanSettingsInput, GetMalwareScanSettingsOutput, Any, Any],
    Interceptor[GetMasterAccountInput, GetMasterAccountOutput, Any, Any],
    Interceptor[GetMemberDetectorsInput, GetMemberDetectorsOutput, Any, Any],
    Interceptor[GetMembersInput, GetMembersOutput, Any, Any],
    Interceptor[
        GetOrganizationStatisticsInput, GetOrganizationStatisticsOutput, Any, Any
    ],
    Interceptor[
        GetRemainingFreeTrialDaysInput, GetRemainingFreeTrialDaysOutput, Any, Any
    ],
    Interceptor[GetThreatEntitySetInput, GetThreatEntitySetOutput, Any, Any],
    Interceptor[GetThreatIntelSetInput, GetThreatIntelSetOutput, Any, Any],
    Interceptor[GetTrustedEntitySetInput, GetTrustedEntitySetOutput, Any, Any],
    Interceptor[GetUsageStatisticsInput, GetUsageStatisticsOutput, Any, Any],
    Interceptor[InviteMembersInput, InviteMembersOutput, Any, Any],
    Interceptor[ListCoverageInput, ListCoverageOutput, Any, Any],
    Interceptor[ListDetectorsInput, ListDetectorsOutput, Any, Any],
    Interceptor[ListFiltersInput, ListFiltersOutput, Any, Any],
    Interceptor[ListFindingsInput, ListFindingsOutput, Any, Any],
    Interceptor[ListInvestigationsInput, ListInvestigationsOutput, Any, Any],
    Interceptor[ListInvitationsInput, ListInvitationsOutput, Any, Any],
    Interceptor[ListIPSetsInput, ListIPSetsOutput, Any, Any],
    Interceptor[
        ListMalwareProtectionPlansInput, ListMalwareProtectionPlansOutput, Any, Any
    ],
    Interceptor[ListMalwareScansInput, ListMalwareScansOutput, Any, Any],
    Interceptor[ListMembersInput, ListMembersOutput, Any, Any],
    Interceptor[
        ListOrganizationAdminAccountsInput,
        ListOrganizationAdminAccountsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListPublishingDestinationsInput, ListPublishingDestinationsOutput, Any, Any
    ],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[ListThreatEntitySetsInput, ListThreatEntitySetsOutput, Any, Any],
    Interceptor[ListThreatIntelSetsInput, ListThreatIntelSetsOutput, Any, Any],
    Interceptor[ListTrustedEntitySetsInput, ListTrustedEntitySetsOutput, Any, Any],
    Interceptor[SendObjectMalwareScanInput, SendObjectMalwareScanOutput, Any, Any],
    Interceptor[StartMalwareScanInput, StartMalwareScanOutput, Any, Any],
    Interceptor[StartMonitoringMembersInput, StartMonitoringMembersOutput, Any, Any],
    Interceptor[StopMonitoringMembersInput, StopMonitoringMembersOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UnarchiveFindingsInput, UnarchiveFindingsOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateDetectorInput, UpdateDetectorOutput, Any, Any],
    Interceptor[UpdateFilterInput, UpdateFilterOutput, Any, Any],
    Interceptor[UpdateFindingsFeedbackInput, UpdateFindingsFeedbackOutput, Any, Any],
    Interceptor[UpdateIPSetInput, UpdateIPSetOutput, Any, Any],
    Interceptor[
        UpdateMalwareProtectionPlanInput, UpdateMalwareProtectionPlanOutput, Any, Any
    ],
    Interceptor[
        UpdateMalwareScanSettingsInput, UpdateMalwareScanSettingsOutput, Any, Any
    ],
    Interceptor[UpdateMemberDetectorsInput, UpdateMemberDetectorsOutput, Any, Any],
    Interceptor[
        UpdateOrganizationConfigurationInput,
        UpdateOrganizationConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdatePublishingDestinationInput, UpdatePublishingDestinationOutput, Any, Any
    ],
    Interceptor[UpdateThreatEntitySetInput, UpdateThreatEntitySetOutput, Any, Any],
    Interceptor[UpdateThreatIntelSetInput, UpdateThreatIntelSetOutput, Any, Any],
    Interceptor[UpdateTrustedEntitySetInput, UpdateTrustedEntitySetOutput, Any, Any],
]


class _AsyncGuardDutyConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: ClientProtocol[Any, Any] | None
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: HTTPAuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncGuardDutyConfig(AsyncAwsConfig):
    """GuardDuty configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """The protocol to serialize and deserialize requests with."""

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: HTTPAuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(
            default=None, resolver=EndpointUriResolver("guardduty")
        ),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="guardduty"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: RestJsonClientProtocol(
                _SCHEMA_GUARD_DUTY_API_SERVICE
            )
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="guardduty")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AIOHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncGuardDutyConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncGuardDutyConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
