# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient

from ._private.schemas import (
    AMAZON_BEDROCK_CONTROL_PLANE_SERVICE as _SCHEMA_AMAZON_BEDROCK_CONTROL_PLANE_SERVICE,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    BatchDeleteAdvancedPromptOptimizationJobInput,
    BatchDeleteAdvancedPromptOptimizationJobOutput,
    BatchDeleteEvaluationJobInput,
    BatchDeleteEvaluationJobOutput,
    CancelAutomatedReasoningPolicyBuildWorkflowInput,
    CancelAutomatedReasoningPolicyBuildWorkflowOutput,
    CreateAdvancedPromptOptimizationJobInput,
    CreateAdvancedPromptOptimizationJobOutput,
    CreateAutomatedReasoningPolicyInput,
    CreateAutomatedReasoningPolicyOutput,
    CreateAutomatedReasoningPolicyTestCaseInput,
    CreateAutomatedReasoningPolicyTestCaseOutput,
    CreateAutomatedReasoningPolicyVersionInput,
    CreateAutomatedReasoningPolicyVersionOutput,
    CreateCustomModelDeploymentInput,
    CreateCustomModelDeploymentOutput,
    CreateCustomModelInput,
    CreateCustomModelOutput,
    CreateEvaluationJobInput,
    CreateEvaluationJobOutput,
    CreateFoundationModelAgreementInput,
    CreateFoundationModelAgreementOutput,
    CreateGuardrailInput,
    CreateGuardrailOutput,
    CreateGuardrailVersionInput,
    CreateGuardrailVersionOutput,
    CreateInferenceProfileInput,
    CreateInferenceProfileOutput,
    CreateMarketplaceModelEndpointInput,
    CreateMarketplaceModelEndpointOutput,
    CreateModelCopyJobInput,
    CreateModelCopyJobOutput,
    CreateModelCustomizationJobInput,
    CreateModelCustomizationJobOutput,
    CreateModelImportJobInput,
    CreateModelImportJobOutput,
    CreateModelInvocationJobInput,
    CreateModelInvocationJobOutput,
    CreatePromptRouterInput,
    CreatePromptRouterOutput,
    CreateProvisionedModelThroughputInput,
    CreateProvisionedModelThroughputOutput,
    DeleteAutomatedReasoningPolicyBuildWorkflowInput,
    DeleteAutomatedReasoningPolicyBuildWorkflowOutput,
    DeleteAutomatedReasoningPolicyInput,
    DeleteAutomatedReasoningPolicyOutput,
    DeleteAutomatedReasoningPolicyTestCaseInput,
    DeleteAutomatedReasoningPolicyTestCaseOutput,
    DeleteCustomModelDeploymentInput,
    DeleteCustomModelDeploymentOutput,
    DeleteCustomModelInput,
    DeleteCustomModelOutput,
    DeleteEnforcedGuardrailConfigurationInput,
    DeleteEnforcedGuardrailConfigurationOutput,
    DeleteFoundationModelAgreementInput,
    DeleteFoundationModelAgreementOutput,
    DeleteGuardrailInput,
    DeleteGuardrailOutput,
    DeleteImportedModelInput,
    DeleteImportedModelOutput,
    DeleteInferenceProfileInput,
    DeleteInferenceProfileOutput,
    DeleteMarketplaceModelEndpointInput,
    DeleteMarketplaceModelEndpointOutput,
    DeleteModelInvocationLoggingConfigurationInput,
    DeleteModelInvocationLoggingConfigurationOutput,
    DeletePromptRouterInput,
    DeletePromptRouterOutput,
    DeleteProvisionedModelThroughputInput,
    DeleteProvisionedModelThroughputOutput,
    DeleteResourcePolicyInput,
    DeleteResourcePolicyOutput,
    DeregisterMarketplaceModelEndpointInput,
    DeregisterMarketplaceModelEndpointOutput,
    ExportAutomatedReasoningPolicyVersionInput,
    ExportAutomatedReasoningPolicyVersionOutput,
    GetAccountDataRetentionInput,
    GetAccountDataRetentionOutput,
    GetAdvancedPromptOptimizationJobInput,
    GetAdvancedPromptOptimizationJobOutput,
    GetAutomatedReasoningPolicyAnnotationsInput,
    GetAutomatedReasoningPolicyAnnotationsOutput,
    GetAutomatedReasoningPolicyBuildWorkflowInput,
    GetAutomatedReasoningPolicyBuildWorkflowOutput,
    GetAutomatedReasoningPolicyBuildWorkflowResultAssetsInput,
    GetAutomatedReasoningPolicyBuildWorkflowResultAssetsOutput,
    GetAutomatedReasoningPolicyInput,
    GetAutomatedReasoningPolicyNextScenarioInput,
    GetAutomatedReasoningPolicyNextScenarioOutput,
    GetAutomatedReasoningPolicyOutput,
    GetAutomatedReasoningPolicyTestCaseInput,
    GetAutomatedReasoningPolicyTestCaseOutput,
    GetAutomatedReasoningPolicyTestResultInput,
    GetAutomatedReasoningPolicyTestResultOutput,
    GetCustomModelDeploymentInput,
    GetCustomModelDeploymentOutput,
    GetCustomModelInput,
    GetCustomModelOutput,
    GetEvaluationJobInput,
    GetEvaluationJobOutput,
    GetFoundationModelAvailabilityInput,
    GetFoundationModelAvailabilityOutput,
    GetFoundationModelInput,
    GetFoundationModelOutput,
    GetGuardrailInput,
    GetGuardrailOutput,
    GetImportedModelInput,
    GetImportedModelOutput,
    GetInferenceProfileInput,
    GetInferenceProfileOutput,
    GetMarketplaceModelEndpointInput,
    GetMarketplaceModelEndpointOutput,
    GetModelCopyJobInput,
    GetModelCopyJobOutput,
    GetModelCustomizationJobInput,
    GetModelCustomizationJobOutput,
    GetModelImportJobInput,
    GetModelImportJobOutput,
    GetModelInvocationJobInput,
    GetModelInvocationJobOutput,
    GetModelInvocationLoggingConfigurationInput,
    GetModelInvocationLoggingConfigurationOutput,
    GetPromptRouterInput,
    GetPromptRouterOutput,
    GetProvisionedModelThroughputInput,
    GetProvisionedModelThroughputOutput,
    GetResourcePolicyInput,
    GetResourcePolicyOutput,
    GetUseCaseForModelAccessInput,
    GetUseCaseForModelAccessOutput,
    ListAdvancedPromptOptimizationJobsInput,
    ListAdvancedPromptOptimizationJobsOutput,
    ListAutomatedReasoningPoliciesInput,
    ListAutomatedReasoningPoliciesOutput,
    ListAutomatedReasoningPolicyBuildWorkflowsInput,
    ListAutomatedReasoningPolicyBuildWorkflowsOutput,
    ListAutomatedReasoningPolicyTestCasesInput,
    ListAutomatedReasoningPolicyTestCasesOutput,
    ListAutomatedReasoningPolicyTestResultsInput,
    ListAutomatedReasoningPolicyTestResultsOutput,
    ListCustomModelDeploymentsInput,
    ListCustomModelDeploymentsOutput,
    ListCustomModelsInput,
    ListCustomModelsOutput,
    ListEnforcedGuardrailsConfigurationInput,
    ListEnforcedGuardrailsConfigurationOutput,
    ListEvaluationJobsInput,
    ListEvaluationJobsOutput,
    ListFoundationModelAgreementOffersInput,
    ListFoundationModelAgreementOffersOutput,
    ListFoundationModelsInput,
    ListFoundationModelsOutput,
    ListGuardrailsInput,
    ListGuardrailsOutput,
    ListImportedModelsInput,
    ListImportedModelsOutput,
    ListInferenceProfilesInput,
    ListInferenceProfilesOutput,
    ListMarketplaceModelEndpointsInput,
    ListMarketplaceModelEndpointsOutput,
    ListModelCopyJobsInput,
    ListModelCopyJobsOutput,
    ListModelCustomizationJobsInput,
    ListModelCustomizationJobsOutput,
    ListModelImportJobsInput,
    ListModelImportJobsOutput,
    ListModelInvocationJobsInput,
    ListModelInvocationJobsOutput,
    ListPromptRoutersInput,
    ListPromptRoutersOutput,
    ListProvisionedModelThroughputsInput,
    ListProvisionedModelThroughputsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    PutAccountDataRetentionInput,
    PutAccountDataRetentionOutput,
    PutEnforcedGuardrailConfigurationInput,
    PutEnforcedGuardrailConfigurationOutput,
    PutModelInvocationLoggingConfigurationInput,
    PutModelInvocationLoggingConfigurationOutput,
    PutResourcePolicyInput,
    PutResourcePolicyOutput,
    PutUseCaseForModelAccessInput,
    PutUseCaseForModelAccessOutput,
    RegisterMarketplaceModelEndpointInput,
    RegisterMarketplaceModelEndpointOutput,
    StartAutomatedReasoningPolicyBuildWorkflowInput,
    StartAutomatedReasoningPolicyBuildWorkflowOutput,
    StartAutomatedReasoningPolicyTestWorkflowInput,
    StartAutomatedReasoningPolicyTestWorkflowOutput,
    StopAdvancedPromptOptimizationJobInput,
    StopAdvancedPromptOptimizationJobOutput,
    StopEvaluationJobInput,
    StopEvaluationJobOutput,
    StopModelCustomizationJobInput,
    StopModelCustomizationJobOutput,
    StopModelInvocationJobInput,
    StopModelInvocationJobOutput,
    TagResourceInput,
    TagResourceOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateAutomatedReasoningPolicyAnnotationsInput,
    UpdateAutomatedReasoningPolicyAnnotationsOutput,
    UpdateAutomatedReasoningPolicyInput,
    UpdateAutomatedReasoningPolicyOutput,
    UpdateAutomatedReasoningPolicyTestCaseInput,
    UpdateAutomatedReasoningPolicyTestCaseOutput,
    UpdateCustomModelDeploymentInput,
    UpdateCustomModelDeploymentOutput,
    UpdateGuardrailInput,
    UpdateGuardrailOutput,
    UpdateMarketplaceModelEndpointInput,
    UpdateMarketplaceModelEndpointOutput,
    UpdateProvisionedModelThroughputInput,
    UpdateProvisionedModelThroughputOutput,
)


_ServiceInterceptor = Union[
    Interceptor[
        BatchDeleteAdvancedPromptOptimizationJobInput,
        BatchDeleteAdvancedPromptOptimizationJobOutput,
        Any,
        Any,
    ],
    Interceptor[
        BatchDeleteEvaluationJobInput, BatchDeleteEvaluationJobOutput, Any, Any
    ],
    Interceptor[
        CancelAutomatedReasoningPolicyBuildWorkflowInput,
        CancelAutomatedReasoningPolicyBuildWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateAdvancedPromptOptimizationJobInput,
        CreateAdvancedPromptOptimizationJobOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateAutomatedReasoningPolicyInput,
        CreateAutomatedReasoningPolicyOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateAutomatedReasoningPolicyTestCaseInput,
        CreateAutomatedReasoningPolicyTestCaseOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateAutomatedReasoningPolicyVersionInput,
        CreateAutomatedReasoningPolicyVersionOutput,
        Any,
        Any,
    ],
    Interceptor[CreateCustomModelInput, CreateCustomModelOutput, Any, Any],
    Interceptor[
        CreateCustomModelDeploymentInput, CreateCustomModelDeploymentOutput, Any, Any
    ],
    Interceptor[CreateEvaluationJobInput, CreateEvaluationJobOutput, Any, Any],
    Interceptor[
        CreateFoundationModelAgreementInput,
        CreateFoundationModelAgreementOutput,
        Any,
        Any,
    ],
    Interceptor[CreateGuardrailInput, CreateGuardrailOutput, Any, Any],
    Interceptor[CreateGuardrailVersionInput, CreateGuardrailVersionOutput, Any, Any],
    Interceptor[CreateInferenceProfileInput, CreateInferenceProfileOutput, Any, Any],
    Interceptor[
        CreateMarketplaceModelEndpointInput,
        CreateMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[CreateModelCopyJobInput, CreateModelCopyJobOutput, Any, Any],
    Interceptor[
        CreateModelCustomizationJobInput, CreateModelCustomizationJobOutput, Any, Any
    ],
    Interceptor[CreateModelImportJobInput, CreateModelImportJobOutput, Any, Any],
    Interceptor[
        CreateModelInvocationJobInput, CreateModelInvocationJobOutput, Any, Any
    ],
    Interceptor[CreatePromptRouterInput, CreatePromptRouterOutput, Any, Any],
    Interceptor[
        CreateProvisionedModelThroughputInput,
        CreateProvisionedModelThroughputOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteAutomatedReasoningPolicyInput,
        DeleteAutomatedReasoningPolicyOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteAutomatedReasoningPolicyBuildWorkflowInput,
        DeleteAutomatedReasoningPolicyBuildWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteAutomatedReasoningPolicyTestCaseInput,
        DeleteAutomatedReasoningPolicyTestCaseOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteCustomModelInput, DeleteCustomModelOutput, Any, Any],
    Interceptor[
        DeleteCustomModelDeploymentInput, DeleteCustomModelDeploymentOutput, Any, Any
    ],
    Interceptor[
        DeleteEnforcedGuardrailConfigurationInput,
        DeleteEnforcedGuardrailConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteFoundationModelAgreementInput,
        DeleteFoundationModelAgreementOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteGuardrailInput, DeleteGuardrailOutput, Any, Any],
    Interceptor[DeleteImportedModelInput, DeleteImportedModelOutput, Any, Any],
    Interceptor[DeleteInferenceProfileInput, DeleteInferenceProfileOutput, Any, Any],
    Interceptor[
        DeleteMarketplaceModelEndpointInput,
        DeleteMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteModelInvocationLoggingConfigurationInput,
        DeleteModelInvocationLoggingConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[DeletePromptRouterInput, DeletePromptRouterOutput, Any, Any],
    Interceptor[
        DeleteProvisionedModelThroughputInput,
        DeleteProvisionedModelThroughputOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteResourcePolicyInput, DeleteResourcePolicyOutput, Any, Any],
    Interceptor[
        DeregisterMarketplaceModelEndpointInput,
        DeregisterMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[
        ExportAutomatedReasoningPolicyVersionInput,
        ExportAutomatedReasoningPolicyVersionOutput,
        Any,
        Any,
    ],
    Interceptor[GetAccountDataRetentionInput, GetAccountDataRetentionOutput, Any, Any],
    Interceptor[
        GetAdvancedPromptOptimizationJobInput,
        GetAdvancedPromptOptimizationJobOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyInput, GetAutomatedReasoningPolicyOutput, Any, Any
    ],
    Interceptor[
        GetAutomatedReasoningPolicyAnnotationsInput,
        GetAutomatedReasoningPolicyAnnotationsOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyBuildWorkflowInput,
        GetAutomatedReasoningPolicyBuildWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyBuildWorkflowResultAssetsInput,
        GetAutomatedReasoningPolicyBuildWorkflowResultAssetsOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyNextScenarioInput,
        GetAutomatedReasoningPolicyNextScenarioOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyTestCaseInput,
        GetAutomatedReasoningPolicyTestCaseOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyTestResultInput,
        GetAutomatedReasoningPolicyTestResultOutput,
        Any,
        Any,
    ],
    Interceptor[GetCustomModelInput, GetCustomModelOutput, Any, Any],
    Interceptor[
        GetCustomModelDeploymentInput, GetCustomModelDeploymentOutput, Any, Any
    ],
    Interceptor[GetEvaluationJobInput, GetEvaluationJobOutput, Any, Any],
    Interceptor[GetFoundationModelInput, GetFoundationModelOutput, Any, Any],
    Interceptor[
        GetFoundationModelAvailabilityInput,
        GetFoundationModelAvailabilityOutput,
        Any,
        Any,
    ],
    Interceptor[GetGuardrailInput, GetGuardrailOutput, Any, Any],
    Interceptor[GetImportedModelInput, GetImportedModelOutput, Any, Any],
    Interceptor[GetInferenceProfileInput, GetInferenceProfileOutput, Any, Any],
    Interceptor[
        GetMarketplaceModelEndpointInput, GetMarketplaceModelEndpointOutput, Any, Any
    ],
    Interceptor[GetModelCopyJobInput, GetModelCopyJobOutput, Any, Any],
    Interceptor[
        GetModelCustomizationJobInput, GetModelCustomizationJobOutput, Any, Any
    ],
    Interceptor[GetModelImportJobInput, GetModelImportJobOutput, Any, Any],
    Interceptor[GetModelInvocationJobInput, GetModelInvocationJobOutput, Any, Any],
    Interceptor[
        GetModelInvocationLoggingConfigurationInput,
        GetModelInvocationLoggingConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[GetPromptRouterInput, GetPromptRouterOutput, Any, Any],
    Interceptor[
        GetProvisionedModelThroughputInput,
        GetProvisionedModelThroughputOutput,
        Any,
        Any,
    ],
    Interceptor[GetResourcePolicyInput, GetResourcePolicyOutput, Any, Any],
    Interceptor[
        GetUseCaseForModelAccessInput, GetUseCaseForModelAccessOutput, Any, Any
    ],
    Interceptor[
        ListAdvancedPromptOptimizationJobsInput,
        ListAdvancedPromptOptimizationJobsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListAutomatedReasoningPoliciesInput,
        ListAutomatedReasoningPoliciesOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListAutomatedReasoningPolicyBuildWorkflowsInput,
        ListAutomatedReasoningPolicyBuildWorkflowsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListAutomatedReasoningPolicyTestCasesInput,
        ListAutomatedReasoningPolicyTestCasesOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListAutomatedReasoningPolicyTestResultsInput,
        ListAutomatedReasoningPolicyTestResultsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListCustomModelDeploymentsInput, ListCustomModelDeploymentsOutput, Any, Any
    ],
    Interceptor[ListCustomModelsInput, ListCustomModelsOutput, Any, Any],
    Interceptor[
        ListEnforcedGuardrailsConfigurationInput,
        ListEnforcedGuardrailsConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[ListEvaluationJobsInput, ListEvaluationJobsOutput, Any, Any],
    Interceptor[
        ListFoundationModelAgreementOffersInput,
        ListFoundationModelAgreementOffersOutput,
        Any,
        Any,
    ],
    Interceptor[ListFoundationModelsInput, ListFoundationModelsOutput, Any, Any],
    Interceptor[ListGuardrailsInput, ListGuardrailsOutput, Any, Any],
    Interceptor[ListImportedModelsInput, ListImportedModelsOutput, Any, Any],
    Interceptor[ListInferenceProfilesInput, ListInferenceProfilesOutput, Any, Any],
    Interceptor[
        ListMarketplaceModelEndpointsInput,
        ListMarketplaceModelEndpointsOutput,
        Any,
        Any,
    ],
    Interceptor[ListModelCopyJobsInput, ListModelCopyJobsOutput, Any, Any],
    Interceptor[
        ListModelCustomizationJobsInput, ListModelCustomizationJobsOutput, Any, Any
    ],
    Interceptor[ListModelImportJobsInput, ListModelImportJobsOutput, Any, Any],
    Interceptor[ListModelInvocationJobsInput, ListModelInvocationJobsOutput, Any, Any],
    Interceptor[ListPromptRoutersInput, ListPromptRoutersOutput, Any, Any],
    Interceptor[
        ListProvisionedModelThroughputsInput,
        ListProvisionedModelThroughputsOutput,
        Any,
        Any,
    ],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[PutAccountDataRetentionInput, PutAccountDataRetentionOutput, Any, Any],
    Interceptor[
        PutEnforcedGuardrailConfigurationInput,
        PutEnforcedGuardrailConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        PutModelInvocationLoggingConfigurationInput,
        PutModelInvocationLoggingConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[PutResourcePolicyInput, PutResourcePolicyOutput, Any, Any],
    Interceptor[
        PutUseCaseForModelAccessInput, PutUseCaseForModelAccessOutput, Any, Any
    ],
    Interceptor[
        RegisterMarketplaceModelEndpointInput,
        RegisterMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[
        StartAutomatedReasoningPolicyBuildWorkflowInput,
        StartAutomatedReasoningPolicyBuildWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        StartAutomatedReasoningPolicyTestWorkflowInput,
        StartAutomatedReasoningPolicyTestWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        StopAdvancedPromptOptimizationJobInput,
        StopAdvancedPromptOptimizationJobOutput,
        Any,
        Any,
    ],
    Interceptor[StopEvaluationJobInput, StopEvaluationJobOutput, Any, Any],
    Interceptor[
        StopModelCustomizationJobInput, StopModelCustomizationJobOutput, Any, Any
    ],
    Interceptor[StopModelInvocationJobInput, StopModelInvocationJobOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[
        UpdateAutomatedReasoningPolicyInput,
        UpdateAutomatedReasoningPolicyOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateAutomatedReasoningPolicyAnnotationsInput,
        UpdateAutomatedReasoningPolicyAnnotationsOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateAutomatedReasoningPolicyTestCaseInput,
        UpdateAutomatedReasoningPolicyTestCaseOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateCustomModelDeploymentInput, UpdateCustomModelDeploymentOutput, Any, Any
    ],
    Interceptor[UpdateGuardrailInput, UpdateGuardrailOutput, Any, Any],
    Interceptor[
        UpdateMarketplaceModelEndpointInput,
        UpdateMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateProvisionedModelThroughputInput,
        UpdateProvisionedModelThroughputOutput,
        Any,
        Any,
    ],
]


class _AsyncBedrockConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: ClientProtocol[Any, Any] | None
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: HTTPAuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncBedrockConfig(AsyncAwsConfig):
    """Bedrock configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """The protocol to serialize and deserialize requests with."""

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: HTTPAuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(
            default=None, resolver=EndpointUriResolver("bedrock")
        ),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="bedrock"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: RestJsonClientProtocol(
                _SCHEMA_AMAZON_BEDROCK_CONTROL_PLANE_SERVICE
            )
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="bedrock")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AIOHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncBedrockConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncBedrockConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
