# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.shapes import ShapeID
from smithy_http.aio.crt import AWSCRTHTTPClient

from ._private.schemas import EXPERT_Q as _SCHEMA_EXPERT_Q
from .auth import HTTPAuthSchemeResolver
from .models import (
    AssociatePermissionInput,
    AssociatePermissionOutput,
    BatchDeleteDocumentInput,
    BatchDeleteDocumentOutput,
    BatchPutDocumentInput,
    BatchPutDocumentOutput,
    CancelSubscriptionInput,
    CancelSubscriptionOutput,
    ChatInput,
    ChatOutput,
    ChatSyncInput,
    ChatSyncOutput,
    CheckDocumentAccessInput,
    CheckDocumentAccessOutput,
    CreateAnonymousWebExperienceUrlInput,
    CreateAnonymousWebExperienceUrlOutput,
    CreateApplicationInput,
    CreateApplicationOutput,
    CreateChatResponseConfigurationInput,
    CreateChatResponseConfigurationOutput,
    CreateDataAccessorInput,
    CreateDataAccessorOutput,
    CreateDataSourceInput,
    CreateDataSourceOutput,
    CreateIndexInput,
    CreateIndexOutput,
    CreatePluginInput,
    CreatePluginOutput,
    CreateRetrieverInput,
    CreateRetrieverOutput,
    CreateSubscriptionInput,
    CreateSubscriptionOutput,
    CreateUserInput,
    CreateUserOutput,
    CreateWebExperienceInput,
    CreateWebExperienceOutput,
    DeleteApplicationInput,
    DeleteApplicationOutput,
    DeleteAttachmentInput,
    DeleteAttachmentOutput,
    DeleteChatControlsConfigurationInput,
    DeleteChatControlsConfigurationOutput,
    DeleteChatResponseConfigurationInput,
    DeleteChatResponseConfigurationOutput,
    DeleteConversationInput,
    DeleteConversationOutput,
    DeleteDataAccessorInput,
    DeleteDataAccessorOutput,
    DeleteDataSourceInput,
    DeleteDataSourceOutput,
    DeleteGroupInput,
    DeleteGroupOutput,
    DeleteIndexInput,
    DeleteIndexOutput,
    DeletePluginInput,
    DeletePluginOutput,
    DeleteRetrieverInput,
    DeleteRetrieverOutput,
    DeleteUserInput,
    DeleteUserOutput,
    DeleteWebExperienceInput,
    DeleteWebExperienceOutput,
    DisassociatePermissionInput,
    DisassociatePermissionOutput,
    GetApplicationInput,
    GetApplicationOutput,
    GetChatControlsConfigurationInput,
    GetChatControlsConfigurationOutput,
    GetChatResponseConfigurationInput,
    GetChatResponseConfigurationOutput,
    GetDataAccessorInput,
    GetDataAccessorOutput,
    GetDataSourceInput,
    GetDataSourceOutput,
    GetDocumentContentInput,
    GetDocumentContentOutput,
    GetGroupInput,
    GetGroupOutput,
    GetIndexInput,
    GetIndexOutput,
    GetMediaInput,
    GetMediaOutput,
    GetPluginInput,
    GetPluginOutput,
    GetPolicyInput,
    GetPolicyOutput,
    GetRetrieverInput,
    GetRetrieverOutput,
    GetUserInput,
    GetUserOutput,
    GetWebExperienceInput,
    GetWebExperienceOutput,
    ListApplicationsInput,
    ListApplicationsOutput,
    ListAttachmentsInput,
    ListAttachmentsOutput,
    ListChatResponseConfigurationsInput,
    ListChatResponseConfigurationsOutput,
    ListConversationsInput,
    ListConversationsOutput,
    ListDataAccessorsInput,
    ListDataAccessorsOutput,
    ListDataSourceSyncJobsInput,
    ListDataSourceSyncJobsOutput,
    ListDataSourcesInput,
    ListDataSourcesOutput,
    ListDocumentsInput,
    ListDocumentsOutput,
    ListGroupsInput,
    ListGroupsOutput,
    ListIndicesInput,
    ListIndicesOutput,
    ListMessagesInput,
    ListMessagesOutput,
    ListPluginActionsInput,
    ListPluginActionsOutput,
    ListPluginTypeActionsInput,
    ListPluginTypeActionsOutput,
    ListPluginTypeMetadataInput,
    ListPluginTypeMetadataOutput,
    ListPluginsInput,
    ListPluginsOutput,
    ListRetrieversInput,
    ListRetrieversOutput,
    ListSubscriptionsInput,
    ListSubscriptionsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    ListWebExperiencesInput,
    ListWebExperiencesOutput,
    PutFeedbackInput,
    PutFeedbackOutput,
    PutGroupInput,
    PutGroupOutput,
    SearchRelevantContentInput,
    SearchRelevantContentOutput,
    StartDataSourceSyncJobInput,
    StartDataSourceSyncJobOutput,
    StopDataSourceSyncJobInput,
    StopDataSourceSyncJobOutput,
    TagResourceInput,
    TagResourceOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateApplicationInput,
    UpdateApplicationOutput,
    UpdateChatControlsConfigurationInput,
    UpdateChatControlsConfigurationOutput,
    UpdateChatResponseConfigurationInput,
    UpdateChatResponseConfigurationOutput,
    UpdateDataAccessorInput,
    UpdateDataAccessorOutput,
    UpdateDataSourceInput,
    UpdateDataSourceOutput,
    UpdateIndexInput,
    UpdateIndexOutput,
    UpdatePluginInput,
    UpdatePluginOutput,
    UpdateRetrieverInput,
    UpdateRetrieverOutput,
    UpdateSubscriptionInput,
    UpdateSubscriptionOutput,
    UpdateUserInput,
    UpdateUserOutput,
    UpdateWebExperienceInput,
    UpdateWebExperienceOutput,
)


_ServiceInterceptor = Union[
    Interceptor[AssociatePermissionInput, AssociatePermissionOutput, Any, Any],
    Interceptor[BatchDeleteDocumentInput, BatchDeleteDocumentOutput, Any, Any],
    Interceptor[BatchPutDocumentInput, BatchPutDocumentOutput, Any, Any],
    Interceptor[CancelSubscriptionInput, CancelSubscriptionOutput, Any, Any],
    Interceptor[ChatInput, ChatOutput, Any, Any],
    Interceptor[ChatSyncInput, ChatSyncOutput, Any, Any],
    Interceptor[CheckDocumentAccessInput, CheckDocumentAccessOutput, Any, Any],
    Interceptor[
        CreateAnonymousWebExperienceUrlInput,
        CreateAnonymousWebExperienceUrlOutput,
        Any,
        Any,
    ],
    Interceptor[CreateApplicationInput, CreateApplicationOutput, Any, Any],
    Interceptor[
        CreateChatResponseConfigurationInput,
        CreateChatResponseConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[CreateDataAccessorInput, CreateDataAccessorOutput, Any, Any],
    Interceptor[CreateDataSourceInput, CreateDataSourceOutput, Any, Any],
    Interceptor[CreateIndexInput, CreateIndexOutput, Any, Any],
    Interceptor[CreatePluginInput, CreatePluginOutput, Any, Any],
    Interceptor[CreateRetrieverInput, CreateRetrieverOutput, Any, Any],
    Interceptor[CreateSubscriptionInput, CreateSubscriptionOutput, Any, Any],
    Interceptor[CreateUserInput, CreateUserOutput, Any, Any],
    Interceptor[CreateWebExperienceInput, CreateWebExperienceOutput, Any, Any],
    Interceptor[DeleteApplicationInput, DeleteApplicationOutput, Any, Any],
    Interceptor[DeleteAttachmentInput, DeleteAttachmentOutput, Any, Any],
    Interceptor[
        DeleteChatControlsConfigurationInput,
        DeleteChatControlsConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteChatResponseConfigurationInput,
        DeleteChatResponseConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteConversationInput, DeleteConversationOutput, Any, Any],
    Interceptor[DeleteDataAccessorInput, DeleteDataAccessorOutput, Any, Any],
    Interceptor[DeleteDataSourceInput, DeleteDataSourceOutput, Any, Any],
    Interceptor[DeleteGroupInput, DeleteGroupOutput, Any, Any],
    Interceptor[DeleteIndexInput, DeleteIndexOutput, Any, Any],
    Interceptor[DeletePluginInput, DeletePluginOutput, Any, Any],
    Interceptor[DeleteRetrieverInput, DeleteRetrieverOutput, Any, Any],
    Interceptor[DeleteUserInput, DeleteUserOutput, Any, Any],
    Interceptor[DeleteWebExperienceInput, DeleteWebExperienceOutput, Any, Any],
    Interceptor[DisassociatePermissionInput, DisassociatePermissionOutput, Any, Any],
    Interceptor[GetApplicationInput, GetApplicationOutput, Any, Any],
    Interceptor[
        GetChatControlsConfigurationInput, GetChatControlsConfigurationOutput, Any, Any
    ],
    Interceptor[
        GetChatResponseConfigurationInput, GetChatResponseConfigurationOutput, Any, Any
    ],
    Interceptor[GetDataAccessorInput, GetDataAccessorOutput, Any, Any],
    Interceptor[GetDataSourceInput, GetDataSourceOutput, Any, Any],
    Interceptor[GetDocumentContentInput, GetDocumentContentOutput, Any, Any],
    Interceptor[GetGroupInput, GetGroupOutput, Any, Any],
    Interceptor[GetIndexInput, GetIndexOutput, Any, Any],
    Interceptor[GetMediaInput, GetMediaOutput, Any, Any],
    Interceptor[GetPluginInput, GetPluginOutput, Any, Any],
    Interceptor[GetPolicyInput, GetPolicyOutput, Any, Any],
    Interceptor[GetRetrieverInput, GetRetrieverOutput, Any, Any],
    Interceptor[GetUserInput, GetUserOutput, Any, Any],
    Interceptor[GetWebExperienceInput, GetWebExperienceOutput, Any, Any],
    Interceptor[ListApplicationsInput, ListApplicationsOutput, Any, Any],
    Interceptor[ListAttachmentsInput, ListAttachmentsOutput, Any, Any],
    Interceptor[
        ListChatResponseConfigurationsInput,
        ListChatResponseConfigurationsOutput,
        Any,
        Any,
    ],
    Interceptor[ListConversationsInput, ListConversationsOutput, Any, Any],
    Interceptor[ListDataAccessorsInput, ListDataAccessorsOutput, Any, Any],
    Interceptor[ListDataSourcesInput, ListDataSourcesOutput, Any, Any],
    Interceptor[ListDataSourceSyncJobsInput, ListDataSourceSyncJobsOutput, Any, Any],
    Interceptor[ListDocumentsInput, ListDocumentsOutput, Any, Any],
    Interceptor[ListGroupsInput, ListGroupsOutput, Any, Any],
    Interceptor[ListIndicesInput, ListIndicesOutput, Any, Any],
    Interceptor[ListMessagesInput, ListMessagesOutput, Any, Any],
    Interceptor[ListPluginActionsInput, ListPluginActionsOutput, Any, Any],
    Interceptor[ListPluginsInput, ListPluginsOutput, Any, Any],
    Interceptor[ListPluginTypeActionsInput, ListPluginTypeActionsOutput, Any, Any],
    Interceptor[ListPluginTypeMetadataInput, ListPluginTypeMetadataOutput, Any, Any],
    Interceptor[ListRetrieversInput, ListRetrieversOutput, Any, Any],
    Interceptor[ListSubscriptionsInput, ListSubscriptionsOutput, Any, Any],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[ListWebExperiencesInput, ListWebExperiencesOutput, Any, Any],
    Interceptor[PutFeedbackInput, PutFeedbackOutput, Any, Any],
    Interceptor[PutGroupInput, PutGroupOutput, Any, Any],
    Interceptor[SearchRelevantContentInput, SearchRelevantContentOutput, Any, Any],
    Interceptor[StartDataSourceSyncJobInput, StartDataSourceSyncJobOutput, Any, Any],
    Interceptor[StopDataSourceSyncJobInput, StopDataSourceSyncJobOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateApplicationInput, UpdateApplicationOutput, Any, Any],
    Interceptor[
        UpdateChatControlsConfigurationInput,
        UpdateChatControlsConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateChatResponseConfigurationInput,
        UpdateChatResponseConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[UpdateDataAccessorInput, UpdateDataAccessorOutput, Any, Any],
    Interceptor[UpdateDataSourceInput, UpdateDataSourceOutput, Any, Any],
    Interceptor[UpdateIndexInput, UpdateIndexOutput, Any, Any],
    Interceptor[UpdatePluginInput, UpdatePluginOutput, Any, Any],
    Interceptor[UpdateRetrieverInput, UpdateRetrieverOutput, Any, Any],
    Interceptor[UpdateSubscriptionInput, UpdateSubscriptionOutput, Any, Any],
    Interceptor[UpdateUserInput, UpdateUserOutput, Any, Any],
    Interceptor[UpdateWebExperienceInput, UpdateWebExperienceOutput, Any, Any],
]


class _AsyncQBusinessConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: ClientProtocol[Any, Any] | None
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: HTTPAuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncQBusinessConfig(AsyncAwsConfig):
    """QBusiness configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """The protocol to serialize and deserialize requests with."""

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: HTTPAuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(
            default=None, resolver=EndpointUriResolver("qbusiness")
        ),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="qbusiness"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: RestJsonClientProtocol(_SCHEMA_EXPERT_Q)
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="qbusiness")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AWSCRTHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncQBusinessConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncQBusinessConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
