# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import AwsJson10ClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient

from ._private.schemas import DYNAMO_DB_20120810 as _SCHEMA_DYNAMO_DB_20120810
from .auth import HTTPAuthSchemeResolver
from .models import (
    BatchExecuteStatementInput,
    BatchExecuteStatementOutput,
    BatchGetItemInput,
    BatchGetItemOutput,
    BatchWriteItemInput,
    BatchWriteItemOutput,
    CreateBackupInput,
    CreateBackupOutput,
    CreateGlobalTableInput,
    CreateGlobalTableOutput,
    CreateTableInput,
    CreateTableOutput,
    DeleteBackupInput,
    DeleteBackupOutput,
    DeleteItemInput,
    DeleteItemOutput,
    DeleteResourcePolicyInput,
    DeleteResourcePolicyOutput,
    DeleteTableInput,
    DeleteTableOutput,
    DescribeBackupInput,
    DescribeBackupOutput,
    DescribeContinuousBackupsInput,
    DescribeContinuousBackupsOutput,
    DescribeContributorInsightsInput,
    DescribeContributorInsightsOutput,
    DescribeEndpointsInput,
    DescribeEndpointsOutput,
    DescribeExportInput,
    DescribeExportOutput,
    DescribeGlobalTableInput,
    DescribeGlobalTableOutput,
    DescribeGlobalTableSettingsInput,
    DescribeGlobalTableSettingsOutput,
    DescribeImportInput,
    DescribeImportOutput,
    DescribeKinesisStreamingDestinationInput,
    DescribeKinesisStreamingDestinationOutput,
    DescribeLimitsInput,
    DescribeLimitsOutput,
    DescribeTableInput,
    DescribeTableOutput,
    DescribeTableReplicaAutoScalingInput,
    DescribeTableReplicaAutoScalingOutput,
    DescribeTimeToLiveInput,
    DescribeTimeToLiveOutput,
    DisableKinesisStreamingDestinationInput,
    DisableKinesisStreamingDestinationOutput,
    EnableKinesisStreamingDestinationInput,
    EnableKinesisStreamingDestinationOutput,
    ExecuteStatementInput,
    ExecuteStatementOutput,
    ExecuteTransactionInput,
    ExecuteTransactionOutput,
    ExportTableToPointInTimeInput,
    ExportTableToPointInTimeOutput,
    GetItemInput,
    GetItemOutput,
    GetResourcePolicyInput,
    GetResourcePolicyOutput,
    ImportTableInput,
    ImportTableOutput,
    ListBackupsInput,
    ListBackupsOutput,
    ListContributorInsightsInput,
    ListContributorInsightsOutput,
    ListExportsInput,
    ListExportsOutput,
    ListGlobalTablesInput,
    ListGlobalTablesOutput,
    ListImportsInput,
    ListImportsOutput,
    ListTablesInput,
    ListTablesOutput,
    ListTagsOfResourceInput,
    ListTagsOfResourceOutput,
    PutItemInput,
    PutItemOutput,
    PutResourcePolicyInput,
    PutResourcePolicyOutput,
    QueryInput,
    QueryOutput,
    RestoreTableFromBackupInput,
    RestoreTableFromBackupOutput,
    RestoreTableToPointInTimeInput,
    RestoreTableToPointInTimeOutput,
    ScanInput,
    ScanOutput,
    SearchVectorsInput,
    SearchVectorsOutput,
    TagResourceInput,
    TagResourceOutput,
    TransactGetItemsInput,
    TransactGetItemsOutput,
    TransactWriteItemsInput,
    TransactWriteItemsOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateContinuousBackupsInput,
    UpdateContinuousBackupsOutput,
    UpdateContributorInsightsInput,
    UpdateContributorInsightsOutput,
    UpdateGlobalTableInput,
    UpdateGlobalTableOutput,
    UpdateGlobalTableSettingsInput,
    UpdateGlobalTableSettingsOutput,
    UpdateItemInput,
    UpdateItemOutput,
    UpdateKinesisStreamingDestinationInput,
    UpdateKinesisStreamingDestinationOutput,
    UpdateTableInput,
    UpdateTableOutput,
    UpdateTableReplicaAutoScalingInput,
    UpdateTableReplicaAutoScalingOutput,
    UpdateTimeToLiveInput,
    UpdateTimeToLiveOutput,
)


_ServiceInterceptor = Union[
    Interceptor[BatchExecuteStatementInput, BatchExecuteStatementOutput, Any, Any],
    Interceptor[BatchGetItemInput, BatchGetItemOutput, Any, Any],
    Interceptor[BatchWriteItemInput, BatchWriteItemOutput, Any, Any],
    Interceptor[CreateBackupInput, CreateBackupOutput, Any, Any],
    Interceptor[CreateGlobalTableInput, CreateGlobalTableOutput, Any, Any],
    Interceptor[CreateTableInput, CreateTableOutput, Any, Any],
    Interceptor[DeleteBackupInput, DeleteBackupOutput, Any, Any],
    Interceptor[DeleteItemInput, DeleteItemOutput, Any, Any],
    Interceptor[DeleteResourcePolicyInput, DeleteResourcePolicyOutput, Any, Any],
    Interceptor[DeleteTableInput, DeleteTableOutput, Any, Any],
    Interceptor[DescribeBackupInput, DescribeBackupOutput, Any, Any],
    Interceptor[
        DescribeContinuousBackupsInput, DescribeContinuousBackupsOutput, Any, Any
    ],
    Interceptor[
        DescribeContributorInsightsInput, DescribeContributorInsightsOutput, Any, Any
    ],
    Interceptor[DescribeEndpointsInput, DescribeEndpointsOutput, Any, Any],
    Interceptor[DescribeExportInput, DescribeExportOutput, Any, Any],
    Interceptor[DescribeGlobalTableInput, DescribeGlobalTableOutput, Any, Any],
    Interceptor[
        DescribeGlobalTableSettingsInput, DescribeGlobalTableSettingsOutput, Any, Any
    ],
    Interceptor[DescribeImportInput, DescribeImportOutput, Any, Any],
    Interceptor[
        DescribeKinesisStreamingDestinationInput,
        DescribeKinesisStreamingDestinationOutput,
        Any,
        Any,
    ],
    Interceptor[DescribeLimitsInput, DescribeLimitsOutput, Any, Any],
    Interceptor[DescribeTableInput, DescribeTableOutput, Any, Any],
    Interceptor[
        DescribeTableReplicaAutoScalingInput,
        DescribeTableReplicaAutoScalingOutput,
        Any,
        Any,
    ],
    Interceptor[DescribeTimeToLiveInput, DescribeTimeToLiveOutput, Any, Any],
    Interceptor[
        DisableKinesisStreamingDestinationInput,
        DisableKinesisStreamingDestinationOutput,
        Any,
        Any,
    ],
    Interceptor[
        EnableKinesisStreamingDestinationInput,
        EnableKinesisStreamingDestinationOutput,
        Any,
        Any,
    ],
    Interceptor[ExecuteStatementInput, ExecuteStatementOutput, Any, Any],
    Interceptor[ExecuteTransactionInput, ExecuteTransactionOutput, Any, Any],
    Interceptor[
        ExportTableToPointInTimeInput, ExportTableToPointInTimeOutput, Any, Any
    ],
    Interceptor[GetItemInput, GetItemOutput, Any, Any],
    Interceptor[GetResourcePolicyInput, GetResourcePolicyOutput, Any, Any],
    Interceptor[ImportTableInput, ImportTableOutput, Any, Any],
    Interceptor[ListBackupsInput, ListBackupsOutput, Any, Any],
    Interceptor[ListContributorInsightsInput, ListContributorInsightsOutput, Any, Any],
    Interceptor[ListExportsInput, ListExportsOutput, Any, Any],
    Interceptor[ListGlobalTablesInput, ListGlobalTablesOutput, Any, Any],
    Interceptor[ListImportsInput, ListImportsOutput, Any, Any],
    Interceptor[ListTablesInput, ListTablesOutput, Any, Any],
    Interceptor[ListTagsOfResourceInput, ListTagsOfResourceOutput, Any, Any],
    Interceptor[PutItemInput, PutItemOutput, Any, Any],
    Interceptor[PutResourcePolicyInput, PutResourcePolicyOutput, Any, Any],
    Interceptor[QueryInput, QueryOutput, Any, Any],
    Interceptor[RestoreTableFromBackupInput, RestoreTableFromBackupOutput, Any, Any],
    Interceptor[
        RestoreTableToPointInTimeInput, RestoreTableToPointInTimeOutput, Any, Any
    ],
    Interceptor[ScanInput, ScanOutput, Any, Any],
    Interceptor[SearchVectorsInput, SearchVectorsOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[TransactGetItemsInput, TransactGetItemsOutput, Any, Any],
    Interceptor[TransactWriteItemsInput, TransactWriteItemsOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateContinuousBackupsInput, UpdateContinuousBackupsOutput, Any, Any],
    Interceptor[
        UpdateContributorInsightsInput, UpdateContributorInsightsOutput, Any, Any
    ],
    Interceptor[UpdateGlobalTableInput, UpdateGlobalTableOutput, Any, Any],
    Interceptor[
        UpdateGlobalTableSettingsInput, UpdateGlobalTableSettingsOutput, Any, Any
    ],
    Interceptor[UpdateItemInput, UpdateItemOutput, Any, Any],
    Interceptor[
        UpdateKinesisStreamingDestinationInput,
        UpdateKinesisStreamingDestinationOutput,
        Any,
        Any,
    ],
    Interceptor[UpdateTableInput, UpdateTableOutput, Any, Any],
    Interceptor[
        UpdateTableReplicaAutoScalingInput,
        UpdateTableReplicaAutoScalingOutput,
        Any,
        Any,
    ],
    Interceptor[UpdateTimeToLiveInput, UpdateTimeToLiveOutput, Any, Any],
]


class _AsyncDynamoDBConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: ClientProtocol[Any, Any] | None
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: HTTPAuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncDynamoDBConfig(AsyncAwsConfig):
    """DynamoDB configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """The protocol to serialize and deserialize requests with."""

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: HTTPAuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(
            default=None, resolver=EndpointUriResolver("dynamodb")
        ),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="dynamodb"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: AwsJson10ClientProtocol(_SCHEMA_DYNAMO_DB_20120810)
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="dynamodb")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AIOHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncDynamoDBConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncDynamoDBConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
