# Code generated by smithy-python-codegen DO NOT EDIT.

from smithy_aws_core.config import ConfigSource
from smithy_core.aio.retries import StandardRetryStrategy
from smithy_core.retries import (
    ExponentialBackoffJitterType,
    ExponentialRetryBackoffStrategy,
    RetryStrategyOptions,
)

from .config import AsyncDynamoDBConfig


_DYNAMODB_DEFAULT_MAX_ATTEMPTS = 4
_DYNAMODB_DEFAULT_BACKOFF_SCALE = 0.025
_DYNAMODB_DEFAULT_MAX_BACKOFF = 20


def dynamodb_retry_plugin(config: AsyncDynamoDBConfig) -> None:
    """Apply DynamoDB's standard-mode retry defaults for any option left unset."""
    retry_strategy = config.retry_strategy
    if retry_strategy is not None and not isinstance(
        retry_strategy, RetryStrategyOptions
    ):
        return

    if isinstance(retry_strategy, RetryStrategyOptions):
        # Explicit options take precedence over separately resolved fields.
        retry_mode = retry_strategy.retry_mode
        max_attempts = retry_strategy.max_attempts
    else:
        # Fall back to the config's independently resolved retry fields.
        retry_mode = config.retry_mode or "standard"
        max_attempts = config.max_attempts
        if config.source_of("max_attempts") == ConfigSource.DEFAULT:
            max_attempts = None

    if retry_mode != "standard":
        return

    config.retry_strategy = StandardRetryStrategy(
        max_attempts=(
            max_attempts if max_attempts is not None else _DYNAMODB_DEFAULT_MAX_ATTEMPTS
        ),
        backoff_strategy=ExponentialRetryBackoffStrategy(
            backoff_scale_value=_DYNAMODB_DEFAULT_BACKOFF_SCALE,
            max_backoff=_DYNAMODB_DEFAULT_MAX_BACKOFF,
            jitter_type=ExponentialBackoffJitterType.FULL,
        ),
    )
