# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient

from ._private.schemas import (
    AMAZON_BEDROCK_KEYSTONE_BUILD_TIME_SERVICE as _SCHEMA_AMAZON_BEDROCK_KEYSTONE_BUILD_TIME_SERVICE,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    CopyBlueprintStageInput,
    CopyBlueprintStageOutput,
    CreateBlueprintInput,
    CreateBlueprintOutput,
    CreateBlueprintVersionInput,
    CreateBlueprintVersionOutput,
    CreateDataAutomationLibraryInput,
    CreateDataAutomationLibraryOutput,
    CreateDataAutomationProjectInput,
    CreateDataAutomationProjectOutput,
    DeleteBlueprintInput,
    DeleteBlueprintOutput,
    DeleteDataAutomationLibraryInput,
    DeleteDataAutomationLibraryOutput,
    DeleteDataAutomationProjectInput,
    DeleteDataAutomationProjectOutput,
    GetBlueprintInput,
    GetBlueprintOptimizationStatusInput,
    GetBlueprintOptimizationStatusOutput,
    GetBlueprintOutput,
    GetDataAutomationLibraryEntityInput,
    GetDataAutomationLibraryEntityOutput,
    GetDataAutomationLibraryIngestionJobInput,
    GetDataAutomationLibraryIngestionJobOutput,
    GetDataAutomationLibraryInput,
    GetDataAutomationLibraryOutput,
    GetDataAutomationProjectInput,
    GetDataAutomationProjectOutput,
    InvokeBlueprintOptimizationAsyncInput,
    InvokeBlueprintOptimizationAsyncOutput,
    InvokeDataAutomationLibraryIngestionJobInput,
    InvokeDataAutomationLibraryIngestionJobOutput,
    ListBlueprintsInput,
    ListBlueprintsOutput,
    ListDataAutomationLibrariesInput,
    ListDataAutomationLibrariesOutput,
    ListDataAutomationLibraryEntitiesInput,
    ListDataAutomationLibraryEntitiesOutput,
    ListDataAutomationLibraryIngestionJobsInput,
    ListDataAutomationLibraryIngestionJobsOutput,
    ListDataAutomationProjectsInput,
    ListDataAutomationProjectsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    TagResourceInput,
    TagResourceOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateBlueprintInput,
    UpdateBlueprintOutput,
    UpdateDataAutomationLibraryInput,
    UpdateDataAutomationLibraryOutput,
    UpdateDataAutomationProjectInput,
    UpdateDataAutomationProjectOutput,
)


_ServiceInterceptor = Union[
    Interceptor[CopyBlueprintStageInput, CopyBlueprintStageOutput, Any, Any],
    Interceptor[CreateBlueprintInput, CreateBlueprintOutput, Any, Any],
    Interceptor[CreateBlueprintVersionInput, CreateBlueprintVersionOutput, Any, Any],
    Interceptor[
        CreateDataAutomationLibraryInput, CreateDataAutomationLibraryOutput, Any, Any
    ],
    Interceptor[
        CreateDataAutomationProjectInput, CreateDataAutomationProjectOutput, Any, Any
    ],
    Interceptor[DeleteBlueprintInput, DeleteBlueprintOutput, Any, Any],
    Interceptor[
        DeleteDataAutomationLibraryInput, DeleteDataAutomationLibraryOutput, Any, Any
    ],
    Interceptor[
        DeleteDataAutomationProjectInput, DeleteDataAutomationProjectOutput, Any, Any
    ],
    Interceptor[GetBlueprintInput, GetBlueprintOutput, Any, Any],
    Interceptor[
        GetBlueprintOptimizationStatusInput,
        GetBlueprintOptimizationStatusOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetDataAutomationLibraryInput, GetDataAutomationLibraryOutput, Any, Any
    ],
    Interceptor[
        GetDataAutomationLibraryEntityInput,
        GetDataAutomationLibraryEntityOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetDataAutomationLibraryIngestionJobInput,
        GetDataAutomationLibraryIngestionJobOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetDataAutomationProjectInput, GetDataAutomationProjectOutput, Any, Any
    ],
    Interceptor[
        InvokeBlueprintOptimizationAsyncInput,
        InvokeBlueprintOptimizationAsyncOutput,
        Any,
        Any,
    ],
    Interceptor[
        InvokeDataAutomationLibraryIngestionJobInput,
        InvokeDataAutomationLibraryIngestionJobOutput,
        Any,
        Any,
    ],
    Interceptor[ListBlueprintsInput, ListBlueprintsOutput, Any, Any],
    Interceptor[
        ListDataAutomationLibrariesInput, ListDataAutomationLibrariesOutput, Any, Any
    ],
    Interceptor[
        ListDataAutomationLibraryEntitiesInput,
        ListDataAutomationLibraryEntitiesOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListDataAutomationLibraryIngestionJobsInput,
        ListDataAutomationLibraryIngestionJobsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListDataAutomationProjectsInput, ListDataAutomationProjectsOutput, Any, Any
    ],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateBlueprintInput, UpdateBlueprintOutput, Any, Any],
    Interceptor[
        UpdateDataAutomationLibraryInput, UpdateDataAutomationLibraryOutput, Any, Any
    ],
    Interceptor[
        UpdateDataAutomationProjectInput, UpdateDataAutomationProjectOutput, Any, Any
    ],
]


class _AsyncBedrockDataAutomationConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: ClientProtocol[Any, Any] | None
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: HTTPAuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncBedrockDataAutomationConfig(AsyncAwsConfig):
    """Bedrock Data Automation configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """The protocol to serialize and deserialize requests with."""

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: HTTPAuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(
            default=None, resolver=EndpointUriResolver("bedrock_data_automation")
        ),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="bedrock-data-automation"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: RestJsonClientProtocol(
                _SCHEMA_AMAZON_BEDROCK_KEYSTONE_BUILD_TIME_SERVICE
            )
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="bedrock")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AIOHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncBedrockDataAutomationConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncBedrockDataAutomationConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
