# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import AwsQueryClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient

from ._private.schemas import (
    AWS_SECURITY_TOKEN_SERVICE_V20110615 as _SCHEMA_AWS_SECURITY_TOKEN_SERVICE_V20110615,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    AssumeRoleInput,
    AssumeRoleOutput,
    AssumeRoleWithSAMLInput,
    AssumeRoleWithSAMLOutput,
    AssumeRoleWithWebIdentityInput,
    AssumeRoleWithWebIdentityOutput,
    AssumeRootInput,
    AssumeRootOutput,
    DecodeAuthorizationMessageInput,
    DecodeAuthorizationMessageOutput,
    GetAccessKeyInfoInput,
    GetAccessKeyInfoOutput,
    GetCallerIdentityInput,
    GetCallerIdentityOutput,
    GetDelegatedAccessTokenInput,
    GetDelegatedAccessTokenOutput,
    GetFederationTokenInput,
    GetFederationTokenOutput,
    GetSessionTokenInput,
    GetSessionTokenOutput,
    GetWebIdentityTokenInput,
    GetWebIdentityTokenOutput,
)


_ServiceInterceptor = Union[
    Interceptor[AssumeRoleInput, AssumeRoleOutput, Any, Any],
    Interceptor[AssumeRoleWithSAMLInput, AssumeRoleWithSAMLOutput, Any, Any],
    Interceptor[
        AssumeRoleWithWebIdentityInput, AssumeRoleWithWebIdentityOutput, Any, Any
    ],
    Interceptor[AssumeRootInput, AssumeRootOutput, Any, Any],
    Interceptor[
        DecodeAuthorizationMessageInput, DecodeAuthorizationMessageOutput, Any, Any
    ],
    Interceptor[GetAccessKeyInfoInput, GetAccessKeyInfoOutput, Any, Any],
    Interceptor[GetCallerIdentityInput, GetCallerIdentityOutput, Any, Any],
    Interceptor[GetDelegatedAccessTokenInput, GetDelegatedAccessTokenOutput, Any, Any],
    Interceptor[GetFederationTokenInput, GetFederationTokenOutput, Any, Any],
    Interceptor[GetSessionTokenInput, GetSessionTokenOutput, Any, Any],
    Interceptor[GetWebIdentityTokenInput, GetWebIdentityTokenOutput, Any, Any],
]


class _AsyncSTSConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: ClientProtocol[Any, Any] | None
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: HTTPAuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncSTSConfig(AsyncAwsConfig):
    """STS configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """The protocol to serialize and deserialize requests with."""

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: HTTPAuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(default=None, resolver=EndpointUriResolver("sts")),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="sts"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: AwsQueryClientProtocol(
                _SCHEMA_AWS_SECURITY_TOKEN_SERVICE_V20110615, "2011-06-15"
            )
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="sts")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AIOHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncSTSConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncSTSConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
