# Code generated by smithy-python-codegen DO NOT EDIT.

import asyncio
from copy import deepcopy
import logging
from typing import Any, Self, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.aio.utils import close
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin

from .config import AsyncBedrockDataAutomationRuntimeConfig, Plugin
from .models import (
    GET_DATA_AUTOMATION_STATUS,
    GetDataAutomationStatusInput,
    GetDataAutomationStatusOutput,
    INVOKE_DATA_AUTOMATION,
    INVOKE_DATA_AUTOMATION_ASYNC,
    InvokeDataAutomationAsyncInput,
    InvokeDataAutomationAsyncOutput,
    InvokeDataAutomationInput,
    InvokeDataAutomationOutput,
    LIST_TAGS_FOR_RESOURCE,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    TAG_RESOURCE,
    TagResourceInput,
    TagResourceOutput,
    UNTAG_RESOURCE,
    UntagResourceInput,
    UntagResourceOutput,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncBedrockDataAutomationRuntimeClient:
    """Amazon Bedrock Data Automation Runtime"""

    def __init__(
        self,
        config: AsyncBedrockDataAutomationRuntimeConfig | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncBedrockDataAutomationRuntimeClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        self._config = config
        self._plugins = plugins
        self._derive_lock = asyncio.Lock()
        self._setup_done = False
        self._closed = False
        self._retry_strategy_resolver = RetryStrategyResolver()
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> None:
        if not self._setup_done:
            async with self._derive_lock:
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncBedrockDataAutomationRuntimeConfig.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    self._config = config

                    if self._config.aws_credentials_identity_resolver is None:
                        config_context = self._config.resolution_context()
                        config_file = None
                        profile_name = None
                        if config_context is not None:
                            config_file = await config_context.parsed_profiles()
                            if config_context.profile_source is ConfigSource.OVERRIDE:
                                profile_name = config_context.profile_name
                        self._config.aws_credentials_identity_resolver = (
                            await IdentityChain.create(
                                AWSCredentialsIdentity,
                                config_file=config_file,
                                profile_name=profile_name,
                                region_override=self._config.region,
                                http_client=cast(
                                    HTTPClient | None, self._config.transport
                                ),
                            )
                        )
                    self._setup_done = True

    async def close(self) -> None:
        """Close this client and any resources held by its transport."""
        if self._closed:
            return
        async with self._derive_lock:
            if self._closed:
                return
            self._closed = True
            if self._setup_done and self._config is not None:
                await close(self._config.transport)

    async def __aenter__(self) -> Self:
        if self._closed:
            raise RuntimeError("Cannot enter a client that has been closed.")
        return self

    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        await self.close()

    async def get_data_automation_status(
        self, input: GetDataAutomationStatusInput, plugins: list[Plugin] | None = None
    ) -> GetDataAutomationStatusOutput:
        """
        API used to get data automation status.

        Args:
            input:
                An instance of `GetDataAutomationStatusInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationStatusOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_DATA_AUTOMATION_STATUS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def invoke_data_automation(
        self, input: InvokeDataAutomationInput, plugins: list[Plugin] | None = None
    ) -> InvokeDataAutomationOutput:
        """
        Sync API: Invoke data automation.

        Args:
            input:
                An instance of `InvokeDataAutomationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `InvokeDataAutomationOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=INVOKE_DATA_AUTOMATION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def invoke_data_automation_async(
        self, input: InvokeDataAutomationAsyncInput, plugins: list[Plugin] | None = None
    ) -> InvokeDataAutomationAsyncOutput:
        """
        Async API: Invoke data automation.

        Args:
            input:
                An instance of `InvokeDataAutomationAsyncInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `InvokeDataAutomationAsyncOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=INVOKE_DATA_AUTOMATION_ASYNC,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_tags_for_resource(
        self, input: ListTagsForResourceInput, plugins: list[Plugin] | None = None
    ) -> ListTagsForResourceOutput:
        """
        List tags for an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `ListTagsForResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListTagsForResourceOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_TAGS_FOR_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def tag_resource(
        self, input: TagResourceInput, plugins: list[Plugin] | None = None
    ) -> TagResourceOutput:
        """
        Tag an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `TagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `TagResourceOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=TAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def untag_resource(
        self, input: UntagResourceInput, plugins: list[Plugin] | None = None
    ) -> UntagResourceOutput:
        """
        Untag an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `UntagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UntagResourceOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UNTAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)
