# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
import logging
from typing import Any, Literal, Self, Union

from smithy_core.deserializers import ShapeDeserializer
from smithy_core.documents import TypeRegistry
from smithy_core.exceptions import ModeledError, SerializationError
from smithy_core.schemas import APIOperation, Schema
from smithy_core.serializers import ShapeSerializer
from smithy_core.shapes import ShapeID
from smithy_core.types import UnknownEnumMixin

from ._private.schemas import (
    ACCESS_DENIED_EXCEPTION as _SCHEMA_ACCESS_DENIED_EXCEPTION,
    ASSET_PROCESSING_CONFIGURATION as _SCHEMA_ASSET_PROCESSING_CONFIGURATION,
    BLUEPRINT as _SCHEMA_BLUEPRINT,
    DATA_AUTOMATION_CONFIGURATION as _SCHEMA_DATA_AUTOMATION_CONFIGURATION,
    ENCRYPTION_CONFIGURATION as _SCHEMA_ENCRYPTION_CONFIGURATION,
    EVENT_BRIDGE_CONFIGURATION as _SCHEMA_EVENT_BRIDGE_CONFIGURATION,
    GET_DATA_AUTOMATION_STATUS as _SCHEMA_GET_DATA_AUTOMATION_STATUS,
    GET_DATA_AUTOMATION_STATUS_INPUT as _SCHEMA_GET_DATA_AUTOMATION_STATUS_INPUT,
    GET_DATA_AUTOMATION_STATUS_OUTPUT as _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT,
    INPUT_CONFIGURATION as _SCHEMA_INPUT_CONFIGURATION,
    INTERNAL_SERVER_EXCEPTION as _SCHEMA_INTERNAL_SERVER_EXCEPTION,
    INVOKE_DATA_AUTOMATION as _SCHEMA_INVOKE_DATA_AUTOMATION,
    INVOKE_DATA_AUTOMATION_ASYNC as _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC,
    INVOKE_DATA_AUTOMATION_ASYNC_INPUT as _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT,
    INVOKE_DATA_AUTOMATION_ASYNC_OUTPUT as _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_OUTPUT,
    INVOKE_DATA_AUTOMATION_INPUT as _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT,
    INVOKE_DATA_AUTOMATION_OUTPUT as _SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT,
    LIST_TAGS_FOR_RESOURCE as _SCHEMA_LIST_TAGS_FOR_RESOURCE,
    LIST_TAGS_FOR_RESOURCE_INPUT as _SCHEMA_LIST_TAGS_FOR_RESOURCE_INPUT,
    LIST_TAGS_FOR_RESOURCE_OUTPUT as _SCHEMA_LIST_TAGS_FOR_RESOURCE_OUTPUT,
    NOTIFICATION_CONFIGURATION as _SCHEMA_NOTIFICATION_CONFIGURATION,
    OUTPUT_CONFIGURATION as _SCHEMA_OUTPUT_CONFIGURATION,
    OUTPUT_SEGMENT as _SCHEMA_OUTPUT_SEGMENT,
    RESOURCE_NOT_FOUND_EXCEPTION as _SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION,
    SERVICE_QUOTA_EXCEEDED_EXCEPTION as _SCHEMA_SERVICE_QUOTA_EXCEEDED_EXCEPTION,
    SERVICE_UNAVAILABLE_EXCEPTION as _SCHEMA_SERVICE_UNAVAILABLE_EXCEPTION,
    SYNC_INPUT_CONFIGURATION as _SCHEMA_SYNC_INPUT_CONFIGURATION,
    TAG as _SCHEMA_TAG,
    TAG_RESOURCE as _SCHEMA_TAG_RESOURCE,
    TAG_RESOURCE_INPUT as _SCHEMA_TAG_RESOURCE_INPUT,
    TAG_RESOURCE_OUTPUT as _SCHEMA_TAG_RESOURCE_OUTPUT,
    THROTTLING_EXCEPTION as _SCHEMA_THROTTLING_EXCEPTION,
    TIMESTAMP_SEGMENT as _SCHEMA_TIMESTAMP_SEGMENT,
    UNTAG_RESOURCE as _SCHEMA_UNTAG_RESOURCE,
    UNTAG_RESOURCE_INPUT as _SCHEMA_UNTAG_RESOURCE_INPUT,
    UNTAG_RESOURCE_OUTPUT as _SCHEMA_UNTAG_RESOURCE_OUTPUT,
    VALIDATION_EXCEPTION as _SCHEMA_VALIDATION_EXCEPTION,
    VIDEO_ASSET_PROCESSING_CONFIGURATION as _SCHEMA_VIDEO_ASSET_PROCESSING_CONFIGURATION,
    VIDEO_SEGMENT_CONFIGURATION as _SCHEMA_VIDEO_SEGMENT_CONFIGURATION,
)


logger = logging.getLogger(__name__)


class ServiceError(ModeledError):
    """
    Base error for all errors in the service.

    Some exceptions do not extend from this class, including
    synthetic, implicit, and shared exception types.
    """


@dataclass(kw_only=True)
class AccessDeniedException(ServiceError):
    """This exception will be thrown when customer does not have access to API."""

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_ACCESS_DENIED_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_ACCESS_DENIED_EXCEPTION.members["message"], self.message
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_ACCESS_DENIED_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_ACCESS_DENIED_EXCEPTION, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class GetDataAutomationStatusInput:
    """Structure for request of GetDataAutomationStatus API."""

    invocation_arn: str | None = None
    """Invocation arn."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_GET_DATA_AUTOMATION_STATUS_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.invocation_arn is not None:
            serializer.write_string(
                _SCHEMA_GET_DATA_AUTOMATION_STATUS_INPUT.members["invocationArn"],
                self.invocation_arn,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["invocation_arn"] = de.read_string(
                        _SCHEMA_GET_DATA_AUTOMATION_STATUS_INPUT.members[
                            "invocationArn"
                        ]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_GET_DATA_AUTOMATION_STATUS_INPUT, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class OutputConfiguration:
    """Output configuration."""

    s3_uri: str
    """S3 uri."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_OUTPUT_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(
            _SCHEMA_OUTPUT_CONFIGURATION.members["s3Uri"], self.s3_uri
        )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["s3_uri"] = de.read_string(
                        _SCHEMA_OUTPUT_CONFIGURATION.members["s3Uri"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_OUTPUT_CONFIGURATION, consumer=_consumer)
        if "s3_uri" not in kwargs:
            kwargs["s3_uri"] = ""
        return kwargs


class AutomationJobStatus(UnknownEnumMixin, StrEnum):
    """List of status supported by automation jobs"""

    CREATED = "Created"
    IN_PROGRESS = "InProgress"
    SUCCESS = "Success"
    SERVICE_ERROR = "ServiceError"
    CLIENT_ERROR = "ClientError"


@dataclass(kw_only=True)
class GetDataAutomationStatusOutput:
    """Response of GetDataAutomationStatus API."""

    status: AutomationJobStatus | None = None
    """Job Status."""

    error_type: str | None = None
    """Error Type."""

    error_message: str | None = None
    """Error Message."""

    output_configuration: OutputConfiguration | None = None
    """Output configuration."""

    job_submission_time: datetime | None = None
    """Job Submission time."""

    job_completion_time: datetime | None = None
    """Job completion time."""

    job_duration_in_seconds: int | None = None
    """Job duration in seconds."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.status is not None:
            serializer.write_string(
                _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members["status"], self.status
            )

        if self.error_type is not None:
            serializer.write_string(
                _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members["errorType"],
                self.error_type,
            )

        if self.error_message is not None:
            serializer.write_string(
                _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members["errorMessage"],
                self.error_message,
            )

        if self.output_configuration is not None:
            serializer.write_struct(
                _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members[
                    "outputConfiguration"
                ],
                self.output_configuration,
            )

        if self.job_submission_time is not None:
            serializer.write_timestamp(
                _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members["jobSubmissionTime"],
                self.job_submission_time,
            )

        if self.job_completion_time is not None:
            serializer.write_timestamp(
                _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members["jobCompletionTime"],
                self.job_completion_time,
            )

        if self.job_duration_in_seconds is not None:
            serializer.write_integer(
                _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members[
                    "jobDurationInSeconds"
                ],
                self.job_duration_in_seconds,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["status"] = AutomationJobStatus(
                        de.read_string(
                            _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members["status"]
                        )
                    )

                case 1:
                    kwargs["error_type"] = de.read_string(
                        _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members["errorType"]
                    )

                case 2:
                    kwargs["error_message"] = de.read_string(
                        _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members[
                            "errorMessage"
                        ]
                    )

                case 3:
                    kwargs["output_configuration"] = OutputConfiguration.deserialize(de)

                case 4:
                    kwargs["job_submission_time"] = de.read_timestamp(
                        _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members[
                            "jobSubmissionTime"
                        ]
                    )

                case 5:
                    kwargs["job_completion_time"] = de.read_timestamp(
                        _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members[
                            "jobCompletionTime"
                        ]
                    )

                case 6:
                    kwargs["job_duration_in_seconds"] = de.read_integer(
                        _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT.members[
                            "jobDurationInSeconds"
                        ]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class InternalServerException(ServiceError):
    """This exception is for any internal un-expected service errors."""

    fault: Literal["client", "server"] | None = "server"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_INTERNAL_SERVER_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_INTERNAL_SERVER_EXCEPTION.members["message"], self.message
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_INTERNAL_SERVER_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_INTERNAL_SERVER_EXCEPTION, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class ResourceNotFoundException(ServiceError):
    """
    This exception will be thrown when resource provided from customer not
    found.
    """

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION.members["message"], self.message
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class ThrottlingException(ServiceError):
    """This exception will be thrown when customer reached API TPS limit."""

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_THROTTLING_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_THROTTLING_EXCEPTION.members["message"], self.message
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_THROTTLING_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_THROTTLING_EXCEPTION, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class ValidationException(ServiceError):
    """This exception will be thrown when customer provided invalid parameters."""

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_VALIDATION_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_VALIDATION_EXCEPTION.members["message"], self.message
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_VALIDATION_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_VALIDATION_EXCEPTION, consumer=_consumer)
        return kwargs


GET_DATA_AUTOMATION_STATUS = APIOperation(
    input=GetDataAutomationStatusInput,
    output=GetDataAutomationStatusOutput,
    schema=_SCHEMA_GET_DATA_AUTOMATION_STATUS,
    input_schema=_SCHEMA_GET_DATA_AUTOMATION_STATUS_INPUT,
    output_schema=_SCHEMA_GET_DATA_AUTOMATION_STATUS_OUTPUT,
    error_registry=TypeRegistry(
        {
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#AccessDeniedException"
            ): AccessDeniedException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#InternalServerException"
            ): InternalServerException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ResourceNotFoundException"
            ): ResourceNotFoundException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ThrottlingException"
            ): ThrottlingException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ValidationException"
            ): ValidationException,
        }
    ),
    effective_auth_schemes=[ShapeID("aws.auth#sigv4")],
    error_schemas=[
        _SCHEMA_ACCESS_DENIED_EXCEPTION,
        _SCHEMA_INTERNAL_SERVER_EXCEPTION,
        _SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION,
        _SCHEMA_THROTTLING_EXCEPTION,
        _SCHEMA_VALIDATION_EXCEPTION,
    ],
)


class BlueprintStage(UnknownEnumMixin, StrEnum):
    """Blueprint stage enum."""

    DEVELOPMENT = "DEVELOPMENT"
    LIVE = "LIVE"


@dataclass(kw_only=True)
class Blueprint:
    """Structure for single blueprint entity."""

    blueprint_arn: str
    """Arn of blueprint."""

    version: str | None = None
    """Version of blueprint."""

    stage: BlueprintStage | None = None
    """Stage of blueprint."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_BLUEPRINT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(
            _SCHEMA_BLUEPRINT.members["blueprintArn"], self.blueprint_arn
        )
        if self.version is not None:
            serializer.write_string(_SCHEMA_BLUEPRINT.members["version"], self.version)

        if self.stage is not None:
            serializer.write_string(_SCHEMA_BLUEPRINT.members["stage"], self.stage)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["blueprint_arn"] = de.read_string(
                        _SCHEMA_BLUEPRINT.members["blueprintArn"]
                    )

                case 1:
                    kwargs["version"] = de.read_string(
                        _SCHEMA_BLUEPRINT.members["version"]
                    )

                case 2:
                    kwargs["stage"] = BlueprintStage(
                        de.read_string(_SCHEMA_BLUEPRINT.members["stage"])
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_BLUEPRINT, consumer=_consumer)
        if "blueprint_arn" not in kwargs:
            kwargs["blueprint_arn"] = ""
        return kwargs


def _serialize_blueprint_list(
    serializer: ShapeSerializer, schema: Schema, value: list[Blueprint]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_blueprint_list(
    deserializer: ShapeDeserializer, schema: Schema
) -> list[Blueprint]:
    result: list[Blueprint] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(Blueprint.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


class DataAutomationStage(UnknownEnumMixin, StrEnum):
    """Data automation stage."""

    LIVE = "LIVE"
    DEVELOPMENT = "DEVELOPMENT"


@dataclass(kw_only=True)
class DataAutomationConfiguration:
    """Data automation configuration."""

    data_automation_project_arn: str
    """Data automation project arn."""

    stage: DataAutomationStage | None = None
    """Data automation stage."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_DATA_AUTOMATION_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(
            _SCHEMA_DATA_AUTOMATION_CONFIGURATION.members["dataAutomationProjectArn"],
            self.data_automation_project_arn,
        )
        if self.stage is not None:
            serializer.write_string(
                _SCHEMA_DATA_AUTOMATION_CONFIGURATION.members["stage"], self.stage
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["data_automation_project_arn"] = de.read_string(
                        _SCHEMA_DATA_AUTOMATION_CONFIGURATION.members[
                            "dataAutomationProjectArn"
                        ]
                    )

                case 1:
                    kwargs["stage"] = DataAutomationStage(
                        de.read_string(
                            _SCHEMA_DATA_AUTOMATION_CONFIGURATION.members["stage"]
                        )
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_DATA_AUTOMATION_CONFIGURATION, consumer=_consumer
        )
        if "data_automation_project_arn" not in kwargs:
            kwargs["data_automation_project_arn"] = ""
        return kwargs


def _serialize_encryption_context_map(
    serializer: ShapeSerializer, schema: Schema, value: dict[str, str]
) -> None:
    with serializer.begin_map(schema, len(value)) as m:
        value_schema = schema.members["value"]
        for k, v in value.items():
            m.entry(k, lambda vs: vs.write_string(value_schema, v))


def _deserialize_encryption_context_map(
    deserializer: ShapeDeserializer, schema: Schema
) -> dict[str, str]:
    result: dict[str, str] = {}
    value_schema = schema.members["value"]

    def _read_value(k: str, d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result[k] = d.read_string(value_schema)

    deserializer.read_map(schema, _read_value)
    return result


@dataclass(kw_only=True)
class EncryptionConfiguration:
    """Encryption configuration."""

    kms_key_id: str
    """Customer KMS key used for encryption"""

    kms_encryption_context: dict[str, str] | None = None
    """KMS encryption context."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_ENCRYPTION_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(
            _SCHEMA_ENCRYPTION_CONFIGURATION.members["kmsKeyId"], self.kms_key_id
        )
        if self.kms_encryption_context is not None:
            _serialize_encryption_context_map(
                serializer,
                _SCHEMA_ENCRYPTION_CONFIGURATION.members["kmsEncryptionContext"],
                self.kms_encryption_context,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["kms_key_id"] = de.read_string(
                        _SCHEMA_ENCRYPTION_CONFIGURATION.members["kmsKeyId"]
                    )

                case 1:
                    kwargs["kms_encryption_context"] = (
                        _deserialize_encryption_context_map(
                            de,
                            _SCHEMA_ENCRYPTION_CONFIGURATION.members[
                                "kmsEncryptionContext"
                            ],
                        )
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_ENCRYPTION_CONFIGURATION, consumer=_consumer)
        if "kms_key_id" not in kwargs:
            kwargs["kms_key_id"] = ""
        return kwargs


@dataclass(kw_only=True)
class TimestampSegment:
    """Timestamp segment"""

    start_time_millis: int
    """Start timestamp in milliseconds"""

    end_time_millis: int
    """End timestamp in milliseconds"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_TIMESTAMP_SEGMENT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_long(
            _SCHEMA_TIMESTAMP_SEGMENT.members["startTimeMillis"], self.start_time_millis
        )
        serializer.write_long(
            _SCHEMA_TIMESTAMP_SEGMENT.members["endTimeMillis"], self.end_time_millis
        )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["start_time_millis"] = de.read_long(
                        _SCHEMA_TIMESTAMP_SEGMENT.members["startTimeMillis"]
                    )

                case 1:
                    kwargs["end_time_millis"] = de.read_long(
                        _SCHEMA_TIMESTAMP_SEGMENT.members["endTimeMillis"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_TIMESTAMP_SEGMENT, consumer=_consumer)
        if "start_time_millis" not in kwargs:
            kwargs["start_time_millis"] = 0
        if "end_time_millis" not in kwargs:
            kwargs["end_time_millis"] = 0
        return kwargs


@dataclass
class VideoSegmentConfigurationTimestampSegment:
    """Timestamp segment"""

    value: TimestampSegment

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_VIDEO_SEGMENT_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_struct(
            _SCHEMA_VIDEO_SEGMENT_CONFIGURATION.members["timestampSegment"], self.value
        )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(value=TimestampSegment.deserialize(deserializer))


@dataclass
class VideoSegmentConfigurationUnknown:
    """
    Represents an unknown variant.

    If you receive this value, you will need to update your library to receive the
    parsed value.

    This value may not be deliberately sent.
    """

    tag: str

    def serialize(self, serializer: ShapeSerializer):
        raise SerializationError("Unknown union variants may not be serialized.")

    def serialize_members(self, serializer: ShapeSerializer):
        raise SerializationError("Unknown union variants may not be serialized.")

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        raise NotImplementedError()


VideoSegmentConfiguration = Union[
    VideoSegmentConfigurationTimestampSegment | VideoSegmentConfigurationUnknown
]
"""Delimits the segment of the input that will be processed"""


class _VideoSegmentConfigurationDeserializer:
    _result: VideoSegmentConfiguration | None = None

    def deserialize(self, deserializer: ShapeDeserializer) -> VideoSegmentConfiguration:
        self._result = None
        deserializer.read_struct(_SCHEMA_VIDEO_SEGMENT_CONFIGURATION, self._consumer)

        if self._result is None:
            raise SerializationError(
                "Unions must have exactly one value, but found none."
            )

        return self._result

    def _consumer(self, schema: Schema, de: ShapeDeserializer) -> None:
        match schema.expect_member_index():
            case 0:
                self._set_result(
                    VideoSegmentConfigurationTimestampSegment.deserialize(de)
                )

            case _:
                self._set_result(
                    VideoSegmentConfigurationUnknown(tag=schema.expect_member_name())
                )

    def _set_result(self, value: VideoSegmentConfiguration) -> None:
        if self._result is not None:
            raise SerializationError(
                "Unions must have exactly one value, but found more than one."
            )
        self._result = value


@dataclass(kw_only=True)
class VideoAssetProcessingConfiguration:
    """Video asset processing configuration"""

    segment_configuration: VideoSegmentConfiguration | None = None
    """Delimits the segment of the input that will be processed"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_VIDEO_ASSET_PROCESSING_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.segment_configuration is not None:
            serializer.write_struct(
                _SCHEMA_VIDEO_ASSET_PROCESSING_CONFIGURATION.members[
                    "segmentConfiguration"
                ],
                self.segment_configuration,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["segment_configuration"] = (
                        _VideoSegmentConfigurationDeserializer().deserialize(de)
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_VIDEO_ASSET_PROCESSING_CONFIGURATION, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class AssetProcessingConfiguration:
    """Config containing asset processing related knobs for all modalities"""

    video: VideoAssetProcessingConfiguration | None = None
    """Video asset processing configuration"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_ASSET_PROCESSING_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.video is not None:
            serializer.write_struct(
                _SCHEMA_ASSET_PROCESSING_CONFIGURATION.members["video"], self.video
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["video"] = VideoAssetProcessingConfiguration.deserialize(de)

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_ASSET_PROCESSING_CONFIGURATION, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class InputConfiguration:
    """Input configuration."""

    s3_uri: str
    """S3 uri."""

    asset_processing_configuration: AssetProcessingConfiguration | None = None
    """Asset processing configuration"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_INPUT_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(
            _SCHEMA_INPUT_CONFIGURATION.members["s3Uri"], self.s3_uri
        )
        if self.asset_processing_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INPUT_CONFIGURATION.members["assetProcessingConfiguration"],
                self.asset_processing_configuration,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["s3_uri"] = de.read_string(
                        _SCHEMA_INPUT_CONFIGURATION.members["s3Uri"]
                    )

                case 1:
                    kwargs["asset_processing_configuration"] = (
                        AssetProcessingConfiguration.deserialize(de)
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_INPUT_CONFIGURATION, consumer=_consumer)
        if "s3_uri" not in kwargs:
            kwargs["s3_uri"] = ""
        return kwargs


@dataclass(kw_only=True)
class EventBridgeConfiguration:
    """Event bridge configuration."""

    event_bridge_enabled: bool
    """Event bridge flag."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_EVENT_BRIDGE_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_boolean(
            _SCHEMA_EVENT_BRIDGE_CONFIGURATION.members["eventBridgeEnabled"],
            self.event_bridge_enabled,
        )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["event_bridge_enabled"] = de.read_boolean(
                        _SCHEMA_EVENT_BRIDGE_CONFIGURATION.members["eventBridgeEnabled"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_EVENT_BRIDGE_CONFIGURATION, consumer=_consumer)
        if "event_bridge_enabled" not in kwargs:
            kwargs["event_bridge_enabled"] = False
        return kwargs

    @classmethod
    def _smithy_default(cls) -> Self:
        return cls(event_bridge_enabled=False)


@dataclass(kw_only=True)
class NotificationConfiguration:
    """Notification configuration."""

    event_bridge_configuration: EventBridgeConfiguration
    """Event bridge configuration."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_NOTIFICATION_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_struct(
            _SCHEMA_NOTIFICATION_CONFIGURATION.members["eventBridgeConfiguration"],
            self.event_bridge_configuration,
        )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["event_bridge_configuration"] = (
                        EventBridgeConfiguration.deserialize(de)
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_NOTIFICATION_CONFIGURATION, consumer=_consumer)
        if "event_bridge_configuration" not in kwargs:
            kwargs["event_bridge_configuration"] = (
                EventBridgeConfiguration._smithy_default()
            )
        return kwargs


@dataclass(kw_only=True)
class Tag:
    """Key value pair of a tag"""

    key: str
    """Defines the context of the tag."""

    value: str
    """
    Defines the value within the context. e.g.
    `<key=reason, value="training">`{=html}.
    """

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_TAG, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(_SCHEMA_TAG.members["key"], self.key)
        serializer.write_string(_SCHEMA_TAG.members["value"], self.value)

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["key"] = de.read_string(_SCHEMA_TAG.members["key"])

                case 1:
                    kwargs["value"] = de.read_string(_SCHEMA_TAG.members["value"])

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_TAG, consumer=_consumer)
        if "key" not in kwargs:
            kwargs["key"] = ""
        if "value" not in kwargs:
            kwargs["value"] = ""
        return kwargs


def _serialize_tag_list(
    serializer: ShapeSerializer, schema: Schema, value: list[Tag]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_tag_list(deserializer: ShapeDeserializer, schema: Schema) -> list[Tag]:
    result: list[Tag] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(Tag.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


@dataclass(kw_only=True)
class InvokeDataAutomationAsyncInput:
    """Invoke Data Automation Async Request"""

    client_token: str | None = None
    """Idempotency token."""

    input_configuration: InputConfiguration | None = None
    """Input configuration."""

    output_configuration: OutputConfiguration | None = None
    """Output configuration."""

    data_automation_configuration: DataAutomationConfiguration | None = None
    """Data automation configuration."""

    encryption_configuration: EncryptionConfiguration | None = None
    """Encryption configuration."""

    notification_configuration: NotificationConfiguration | None = None
    """Notification configuration."""

    blueprints: list[Blueprint] | None = None
    """Blueprint list."""

    data_automation_profile_arn: str | None = None
    """Data automation profile ARN"""

    tags: list[Tag] | None = None
    """List of tags."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.client_token is not None:
            serializer.write_string(
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members["clientToken"],
                self.client_token,
            )

        if self.input_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                    "inputConfiguration"
                ],
                self.input_configuration,
            )

        if self.output_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                    "outputConfiguration"
                ],
                self.output_configuration,
            )

        if self.data_automation_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                    "dataAutomationConfiguration"
                ],
                self.data_automation_configuration,
            )

        if self.encryption_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                    "encryptionConfiguration"
                ],
                self.encryption_configuration,
            )

        if self.notification_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                    "notificationConfiguration"
                ],
                self.notification_configuration,
            )

        if self.blueprints is not None:
            _serialize_blueprint_list(
                serializer,
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members["blueprints"],
                self.blueprints,
            )

        if self.data_automation_profile_arn is not None:
            serializer.write_string(
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                    "dataAutomationProfileArn"
                ],
                self.data_automation_profile_arn,
            )

        if self.tags is not None:
            _serialize_tag_list(
                serializer,
                _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members["tags"],
                self.tags,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["client_token"] = de.read_string(
                        _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                            "clientToken"
                        ]
                    )

                case 1:
                    kwargs["input_configuration"] = InputConfiguration.deserialize(de)

                case 2:
                    kwargs["output_configuration"] = OutputConfiguration.deserialize(de)

                case 3:
                    kwargs["data_automation_configuration"] = (
                        DataAutomationConfiguration.deserialize(de)
                    )

                case 4:
                    kwargs["encryption_configuration"] = (
                        EncryptionConfiguration.deserialize(de)
                    )

                case 5:
                    kwargs["notification_configuration"] = (
                        NotificationConfiguration.deserialize(de)
                    )

                case 6:
                    kwargs["blueprints"] = _deserialize_blueprint_list(
                        de,
                        _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                            "blueprints"
                        ],
                    )

                case 7:
                    kwargs["data_automation_profile_arn"] = de.read_string(
                        _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members[
                            "dataAutomationProfileArn"
                        ]
                    )

                case 8:
                    kwargs["tags"] = _deserialize_tag_list(
                        de, _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT.members["tags"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class InvokeDataAutomationAsyncOutput:
    """Invoke Data Automation Async Response"""

    invocation_arn: str
    """ARN of the automation job"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        serializer.write_string(
            _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_OUTPUT.members["invocationArn"],
            self.invocation_arn,
        )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["invocation_arn"] = de.read_string(
                        _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_OUTPUT.members[
                            "invocationArn"
                        ]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_OUTPUT, consumer=_consumer
        )
        if "invocation_arn" not in kwargs:
            kwargs["invocation_arn"] = ""
        return kwargs


@dataclass(kw_only=True)
class ServiceQuotaExceededException(ServiceError):
    """This exception will be thrown when service quota is exceeded."""

    fault: Literal["client", "server"] | None = "client"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_SERVICE_QUOTA_EXCEEDED_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_SERVICE_QUOTA_EXCEEDED_EXCEPTION.members["message"],
                self.message,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_SERVICE_QUOTA_EXCEEDED_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_SERVICE_QUOTA_EXCEEDED_EXCEPTION, consumer=_consumer
        )
        return kwargs


INVOKE_DATA_AUTOMATION_ASYNC = APIOperation(
    input=InvokeDataAutomationAsyncInput,
    output=InvokeDataAutomationAsyncOutput,
    schema=_SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC,
    input_schema=_SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_INPUT,
    output_schema=_SCHEMA_INVOKE_DATA_AUTOMATION_ASYNC_OUTPUT,
    error_registry=TypeRegistry(
        {
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#AccessDeniedException"
            ): AccessDeniedException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#InternalServerException"
            ): InternalServerException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ServiceQuotaExceededException"
            ): ServiceQuotaExceededException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ThrottlingException"
            ): ThrottlingException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ValidationException"
            ): ValidationException,
        }
    ),
    effective_auth_schemes=[ShapeID("aws.auth#sigv4")],
    error_schemas=[
        _SCHEMA_ACCESS_DENIED_EXCEPTION,
        _SCHEMA_INTERNAL_SERVER_EXCEPTION,
        _SCHEMA_SERVICE_QUOTA_EXCEEDED_EXCEPTION,
        _SCHEMA_THROTTLING_EXCEPTION,
        _SCHEMA_VALIDATION_EXCEPTION,
    ],
)


@dataclass(kw_only=True)
class SyncInputConfiguration:
    """Input configuration for synchronous API"""

    bytes_: bytes | None = None
    """Input data as bytes"""

    s3_uri: str | None = None
    """S3 URI of the input data"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_SYNC_INPUT_CONFIGURATION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.bytes_ is not None:
            serializer.write_blob(
                _SCHEMA_SYNC_INPUT_CONFIGURATION.members["bytes"], self.bytes_
            )

        if self.s3_uri is not None:
            serializer.write_string(
                _SCHEMA_SYNC_INPUT_CONFIGURATION.members["s3Uri"], self.s3_uri
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["bytes_"] = de.read_blob(
                        _SCHEMA_SYNC_INPUT_CONFIGURATION.members["bytes"]
                    )

                case 1:
                    kwargs["s3_uri"] = de.read_string(
                        _SCHEMA_SYNC_INPUT_CONFIGURATION.members["s3Uri"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_SYNC_INPUT_CONFIGURATION, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class InvokeDataAutomationInput:
    """Invoke Data Automation Request"""

    input_configuration: SyncInputConfiguration | None = None
    """Input configuration."""

    data_automation_configuration: DataAutomationConfiguration | None = None
    """Data automation configuration."""

    blueprints: list[Blueprint] | None = None
    """Blueprint list."""

    data_automation_profile_arn: str | None = None
    """Data automation profile ARN"""

    encryption_configuration: EncryptionConfiguration | None = None
    """Encryption configuration."""

    output_configuration: OutputConfiguration | None = None
    """Output configuration."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_INVOKE_DATA_AUTOMATION_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.input_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT.members["inputConfiguration"],
                self.input_configuration,
            )

        if self.data_automation_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT.members[
                    "dataAutomationConfiguration"
                ],
                self.data_automation_configuration,
            )

        if self.blueprints is not None:
            _serialize_blueprint_list(
                serializer,
                _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT.members["blueprints"],
                self.blueprints,
            )

        if self.data_automation_profile_arn is not None:
            serializer.write_string(
                _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT.members[
                    "dataAutomationProfileArn"
                ],
                self.data_automation_profile_arn,
            )

        if self.encryption_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT.members["encryptionConfiguration"],
                self.encryption_configuration,
            )

        if self.output_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT.members["outputConfiguration"],
                self.output_configuration,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["input_configuration"] = SyncInputConfiguration.deserialize(
                        de
                    )

                case 1:
                    kwargs["data_automation_configuration"] = (
                        DataAutomationConfiguration.deserialize(de)
                    )

                case 2:
                    kwargs["blueprints"] = _deserialize_blueprint_list(
                        de, _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT.members["blueprints"]
                    )

                case 3:
                    kwargs["data_automation_profile_arn"] = de.read_string(
                        _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT.members[
                            "dataAutomationProfileArn"
                        ]
                    )

                case 4:
                    kwargs["encryption_configuration"] = (
                        EncryptionConfiguration.deserialize(de)
                    )

                case 5:
                    kwargs["output_configuration"] = OutputConfiguration.deserialize(de)

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_INVOKE_DATA_AUTOMATION_INPUT, consumer=_consumer
        )
        return kwargs


class CustomOutputStatus(UnknownEnumMixin, StrEnum):
    """Custom output status enum"""

    MATCH = "MATCH"
    NO_MATCH = "NO_MATCH"


@dataclass(kw_only=True)
class OutputSegment:
    """Results for an output segment"""

    custom_output_status: CustomOutputStatus | None = None
    """Status of blueprint match"""

    custom_output: str | None = None
    """Custom output response"""

    standard_output: str | None = None
    """Standard output response"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_OUTPUT_SEGMENT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.custom_output_status is not None:
            serializer.write_string(
                _SCHEMA_OUTPUT_SEGMENT.members["customOutputStatus"],
                self.custom_output_status,
            )

        if self.custom_output is not None:
            serializer.write_string(
                _SCHEMA_OUTPUT_SEGMENT.members["customOutput"], self.custom_output
            )

        if self.standard_output is not None:
            serializer.write_string(
                _SCHEMA_OUTPUT_SEGMENT.members["standardOutput"], self.standard_output
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["custom_output_status"] = CustomOutputStatus(
                        de.read_string(
                            _SCHEMA_OUTPUT_SEGMENT.members["customOutputStatus"]
                        )
                    )

                case 1:
                    kwargs["custom_output"] = de.read_string(
                        _SCHEMA_OUTPUT_SEGMENT.members["customOutput"]
                    )

                case 2:
                    kwargs["standard_output"] = de.read_string(
                        _SCHEMA_OUTPUT_SEGMENT.members["standardOutput"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_OUTPUT_SEGMENT, consumer=_consumer)
        return kwargs


def _serialize_output_segment_list(
    serializer: ShapeSerializer, schema: Schema, value: list[OutputSegment]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_struct(member_schema, e)


def _deserialize_output_segment_list(
    deserializer: ShapeDeserializer, schema: Schema
) -> list[OutputSegment]:
    result: list[OutputSegment] = []

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(OutputSegment.deserialize(d))

    deserializer.read_list(schema, _read_value)
    return result


class SemanticModality(UnknownEnumMixin, StrEnum):
    """Semantic modality enum"""

    DOCUMENT = "DOCUMENT"
    IMAGE = "IMAGE"
    AUDIO = "AUDIO"
    VIDEO = "VIDEO"


@dataclass(kw_only=True)
class InvokeDataAutomationOutput:
    """Invoke Data Automation Response"""

    semantic_modality: SemanticModality
    """Detected semantic modality"""

    output_configuration: OutputConfiguration | None = None
    """Output configuration"""

    output_segments: list[OutputSegment] = field(default_factory=list[OutputSegment])
    """List of outputs for each logical sub-doc"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.output_configuration is not None:
            serializer.write_struct(
                _SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT.members["outputConfiguration"],
                self.output_configuration,
            )

        serializer.write_string(
            _SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT.members["semanticModality"],
            self.semantic_modality,
        )
        _serialize_output_segment_list(
            serializer,
            _SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT.members["outputSegments"],
            self.output_segments,
        )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["output_configuration"] = OutputConfiguration.deserialize(de)

                case 1:
                    kwargs["semantic_modality"] = SemanticModality(
                        de.read_string(
                            _SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT.members[
                                "semanticModality"
                            ]
                        )
                    )

                case 2:
                    kwargs["output_segments"] = _deserialize_output_segment_list(
                        de,
                        _SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT.members["outputSegments"],
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT, consumer=_consumer
        )
        if "semantic_modality" not in kwargs:
            kwargs["semantic_modality"] = SemanticModality._corrected("")
        return kwargs


@dataclass(kw_only=True)
class ServiceUnavailableException(ServiceError):
    """This exception will be thrown when service is temporarily unavailable."""

    fault: Literal["client", "server"] | None = "server"

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_SERVICE_UNAVAILABLE_EXCEPTION, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.message is not None:
            serializer.write_string(
                _SCHEMA_SERVICE_UNAVAILABLE_EXCEPTION.members["message"], self.message
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["message"] = de.read_string(
                        _SCHEMA_SERVICE_UNAVAILABLE_EXCEPTION.members["message"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_SERVICE_UNAVAILABLE_EXCEPTION, consumer=_consumer
        )
        return kwargs


INVOKE_DATA_AUTOMATION = APIOperation(
    input=InvokeDataAutomationInput,
    output=InvokeDataAutomationOutput,
    schema=_SCHEMA_INVOKE_DATA_AUTOMATION,
    input_schema=_SCHEMA_INVOKE_DATA_AUTOMATION_INPUT,
    output_schema=_SCHEMA_INVOKE_DATA_AUTOMATION_OUTPUT,
    error_registry=TypeRegistry(
        {
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#AccessDeniedException"
            ): AccessDeniedException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#InternalServerException"
            ): InternalServerException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ServiceUnavailableException"
            ): ServiceUnavailableException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ThrottlingException"
            ): ThrottlingException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ValidationException"
            ): ValidationException,
        }
    ),
    effective_auth_schemes=[ShapeID("aws.auth#sigv4")],
    error_schemas=[
        _SCHEMA_ACCESS_DENIED_EXCEPTION,
        _SCHEMA_INTERNAL_SERVER_EXCEPTION,
        _SCHEMA_SERVICE_UNAVAILABLE_EXCEPTION,
        _SCHEMA_THROTTLING_EXCEPTION,
        _SCHEMA_VALIDATION_EXCEPTION,
    ],
)


@dataclass(kw_only=True)
class ListTagsForResourceInput:
    """Dataclass for ListTagsForResourceInput structure."""

    resource_arn: str | None = None
    """ARN of a taggable resource"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_LIST_TAGS_FOR_RESOURCE_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.resource_arn is not None:
            serializer.write_string(
                _SCHEMA_LIST_TAGS_FOR_RESOURCE_INPUT.members["resourceARN"],
                self.resource_arn,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["resource_arn"] = de.read_string(
                        _SCHEMA_LIST_TAGS_FOR_RESOURCE_INPUT.members["resourceARN"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_LIST_TAGS_FOR_RESOURCE_INPUT, consumer=_consumer
        )
        return kwargs


@dataclass(kw_only=True)
class ListTagsForResourceOutput:
    """Dataclass for ListTagsForResourceOutput structure."""

    tags: list[Tag] | None = None
    """List of tags"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_LIST_TAGS_FOR_RESOURCE_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.tags is not None:
            _serialize_tag_list(
                serializer,
                _SCHEMA_LIST_TAGS_FOR_RESOURCE_OUTPUT.members["tags"],
                self.tags,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["tags"] = _deserialize_tag_list(
                        de, _SCHEMA_LIST_TAGS_FOR_RESOURCE_OUTPUT.members["tags"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(
            _SCHEMA_LIST_TAGS_FOR_RESOURCE_OUTPUT, consumer=_consumer
        )
        return kwargs


LIST_TAGS_FOR_RESOURCE = APIOperation(
    input=ListTagsForResourceInput,
    output=ListTagsForResourceOutput,
    schema=_SCHEMA_LIST_TAGS_FOR_RESOURCE,
    input_schema=_SCHEMA_LIST_TAGS_FOR_RESOURCE_INPUT,
    output_schema=_SCHEMA_LIST_TAGS_FOR_RESOURCE_OUTPUT,
    error_registry=TypeRegistry(
        {
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#AccessDeniedException"
            ): AccessDeniedException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#InternalServerException"
            ): InternalServerException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ResourceNotFoundException"
            ): ResourceNotFoundException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ThrottlingException"
            ): ThrottlingException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ValidationException"
            ): ValidationException,
        }
    ),
    effective_auth_schemes=[ShapeID("aws.auth#sigv4")],
    error_schemas=[
        _SCHEMA_ACCESS_DENIED_EXCEPTION,
        _SCHEMA_INTERNAL_SERVER_EXCEPTION,
        _SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION,
        _SCHEMA_THROTTLING_EXCEPTION,
        _SCHEMA_VALIDATION_EXCEPTION,
    ],
)


@dataclass(kw_only=True)
class TagResourceInput:
    """Dataclass for TagResourceInput structure."""

    resource_arn: str | None = None
    """ARN of a taggable resource"""

    tags: list[Tag] | None = None
    """List of tags"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_TAG_RESOURCE_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.resource_arn is not None:
            serializer.write_string(
                _SCHEMA_TAG_RESOURCE_INPUT.members["resourceARN"], self.resource_arn
            )

        if self.tags is not None:
            _serialize_tag_list(
                serializer, _SCHEMA_TAG_RESOURCE_INPUT.members["tags"], self.tags
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["resource_arn"] = de.read_string(
                        _SCHEMA_TAG_RESOURCE_INPUT.members["resourceARN"]
                    )

                case 1:
                    kwargs["tags"] = _deserialize_tag_list(
                        de, _SCHEMA_TAG_RESOURCE_INPUT.members["tags"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_TAG_RESOURCE_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class TagResourceOutput:
    """Dataclass for TagResourceOutput structure."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_TAG_RESOURCE_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        pass

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_TAG_RESOURCE_OUTPUT, consumer=_consumer)
        return kwargs


TAG_RESOURCE = APIOperation(
    input=TagResourceInput,
    output=TagResourceOutput,
    schema=_SCHEMA_TAG_RESOURCE,
    input_schema=_SCHEMA_TAG_RESOURCE_INPUT,
    output_schema=_SCHEMA_TAG_RESOURCE_OUTPUT,
    error_registry=TypeRegistry(
        {
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#AccessDeniedException"
            ): AccessDeniedException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#InternalServerException"
            ): InternalServerException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ResourceNotFoundException"
            ): ResourceNotFoundException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ServiceQuotaExceededException"
            ): ServiceQuotaExceededException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ThrottlingException"
            ): ThrottlingException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ValidationException"
            ): ValidationException,
        }
    ),
    effective_auth_schemes=[ShapeID("aws.auth#sigv4")],
    error_schemas=[
        _SCHEMA_ACCESS_DENIED_EXCEPTION,
        _SCHEMA_INTERNAL_SERVER_EXCEPTION,
        _SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION,
        _SCHEMA_SERVICE_QUOTA_EXCEEDED_EXCEPTION,
        _SCHEMA_THROTTLING_EXCEPTION,
        _SCHEMA_VALIDATION_EXCEPTION,
    ],
)


def _serialize_tag_key_list(
    serializer: ShapeSerializer, schema: Schema, value: list[str]
) -> None:
    member_schema = schema.members["member"]
    with serializer.begin_list(schema, len(value)) as ls:
        for e in value:
            ls.write_string(member_schema, e)


def _deserialize_tag_key_list(
    deserializer: ShapeDeserializer, schema: Schema
) -> list[str]:
    result: list[str] = []
    member_schema = schema.members["member"]

    def _read_value(d: ShapeDeserializer):
        if d.is_null():
            d.read_null()

        else:
            result.append(d.read_string(member_schema))

    deserializer.read_list(schema, _read_value)
    return result


@dataclass(kw_only=True)
class UntagResourceInput:
    """Dataclass for UntagResourceInput structure."""

    resource_arn: str | None = None
    """ARN of a taggable resource"""

    tag_keys: list[str] | None = None
    """List of tag keys"""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_UNTAG_RESOURCE_INPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        if self.resource_arn is not None:
            serializer.write_string(
                _SCHEMA_UNTAG_RESOURCE_INPUT.members["resourceARN"], self.resource_arn
            )

        if self.tag_keys is not None:
            _serialize_tag_key_list(
                serializer,
                _SCHEMA_UNTAG_RESOURCE_INPUT.members["tagKeys"],
                self.tag_keys,
            )

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case 0:
                    kwargs["resource_arn"] = de.read_string(
                        _SCHEMA_UNTAG_RESOURCE_INPUT.members["resourceARN"]
                    )

                case 1:
                    kwargs["tag_keys"] = _deserialize_tag_key_list(
                        de, _SCHEMA_UNTAG_RESOURCE_INPUT.members["tagKeys"]
                    )

                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_UNTAG_RESOURCE_INPUT, consumer=_consumer)
        return kwargs


@dataclass(kw_only=True)
class UntagResourceOutput:
    """Dataclass for UntagResourceOutput structure."""

    def serialize(self, serializer: ShapeSerializer):
        serializer.write_struct(_SCHEMA_UNTAG_RESOURCE_OUTPUT, self)

    def serialize_members(self, serializer: ShapeSerializer):
        pass

    @classmethod
    def deserialize(cls, deserializer: ShapeDeserializer) -> Self:
        return cls(**cls.deserialize_kwargs(deserializer))

    @classmethod
    def deserialize_kwargs(cls, deserializer: ShapeDeserializer) -> dict[str, Any]:
        kwargs: dict[str, Any] = {}

        def _consumer(schema: Schema, de: ShapeDeserializer) -> None:
            match schema.expect_member_index():
                case _:
                    logger.debug("Unexpected member schema: %s", schema)

        deserializer.read_struct(_SCHEMA_UNTAG_RESOURCE_OUTPUT, consumer=_consumer)
        return kwargs


UNTAG_RESOURCE = APIOperation(
    input=UntagResourceInput,
    output=UntagResourceOutput,
    schema=_SCHEMA_UNTAG_RESOURCE,
    input_schema=_SCHEMA_UNTAG_RESOURCE_INPUT,
    output_schema=_SCHEMA_UNTAG_RESOURCE_OUTPUT,
    error_registry=TypeRegistry(
        {
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#AccessDeniedException"
            ): AccessDeniedException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#InternalServerException"
            ): InternalServerException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ResourceNotFoundException"
            ): ResourceNotFoundException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ThrottlingException"
            ): ThrottlingException,
            ShapeID(
                "com.amazonaws.bedrockdataautomationruntime#ValidationException"
            ): ValidationException,
        }
    ),
    effective_auth_schemes=[ShapeID("aws.auth#sigv4")],
    error_schemas=[
        _SCHEMA_ACCESS_DENIED_EXCEPTION,
        _SCHEMA_INTERNAL_SERVER_EXCEPTION,
        _SCHEMA_RESOURCE_NOT_FOUND_EXCEPTION,
        _SCHEMA_THROTTLING_EXCEPTION,
        _SCHEMA_VALIDATION_EXCEPTION,
    ],
)
