# Code generated by smithy-python-codegen DO NOT EDIT.

import asyncio
from copy import deepcopy
import logging
from typing import Any, Self, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.aio.utils import close
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin

from .config import AsyncCognitoIdentityConfig, Plugin
from .models import (
    CREATE_IDENTITY_POOL,
    CreateIdentityPoolInput,
    CreateIdentityPoolOutput,
    DELETE_IDENTITIES,
    DELETE_IDENTITY_POOL,
    DESCRIBE_IDENTITY,
    DESCRIBE_IDENTITY_POOL,
    DeleteIdentitiesInput,
    DeleteIdentitiesOutput,
    DeleteIdentityPoolInput,
    DeleteIdentityPoolOutput,
    DescribeIdentityInput,
    DescribeIdentityOutput,
    DescribeIdentityPoolInput,
    DescribeIdentityPoolOutput,
    GET_CREDENTIALS_FOR_IDENTITY,
    GET_ID,
    GET_IDENTITY_POOL_ROLES,
    GET_OPEN_ID_TOKEN,
    GET_OPEN_ID_TOKEN_FOR_DEVELOPER_IDENTITY,
    GET_PRINCIPAL_TAG_ATTRIBUTE_MAP,
    GetCredentialsForIdentityInput,
    GetCredentialsForIdentityOutput,
    GetIdInput,
    GetIdOutput,
    GetIdentityPoolRolesInput,
    GetIdentityPoolRolesOutput,
    GetOpenIdTokenForDeveloperIdentityInput,
    GetOpenIdTokenForDeveloperIdentityOutput,
    GetOpenIdTokenInput,
    GetOpenIdTokenOutput,
    GetPrincipalTagAttributeMapInput,
    GetPrincipalTagAttributeMapOutput,
    LIST_IDENTITIES,
    LIST_IDENTITY_POOLS,
    LIST_TAGS_FOR_RESOURCE,
    LOOKUP_DEVELOPER_IDENTITY,
    ListIdentitiesInput,
    ListIdentitiesOutput,
    ListIdentityPoolsInput,
    ListIdentityPoolsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    LookupDeveloperIdentityInput,
    LookupDeveloperIdentityOutput,
    MERGE_DEVELOPER_IDENTITIES,
    MergeDeveloperIdentitiesInput,
    MergeDeveloperIdentitiesOutput,
    SET_IDENTITY_POOL_ROLES,
    SET_PRINCIPAL_TAG_ATTRIBUTE_MAP,
    SetIdentityPoolRolesInput,
    SetIdentityPoolRolesOutput,
    SetPrincipalTagAttributeMapInput,
    SetPrincipalTagAttributeMapOutput,
    TAG_RESOURCE,
    TagResourceInput,
    TagResourceOutput,
    UNLINK_DEVELOPER_IDENTITY,
    UNLINK_IDENTITY,
    UNTAG_RESOURCE,
    UPDATE_IDENTITY_POOL,
    UnlinkDeveloperIdentityInput,
    UnlinkDeveloperIdentityOutput,
    UnlinkIdentityInput,
    UnlinkIdentityOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateIdentityPoolInput,
    UpdateIdentityPoolOutput,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncCognitoIdentityClient:
    """
    Amazon Cognito Federated Identities is a web service that delivers
    scoped temporary credentials to mobile devices and other untrusted
    environments. It uniquely identifies a device and supplies the user with
    a consistent identity over the lifetime of an application.

    Using Amazon Cognito Federated Identities, you can enable authentication
    with one or more third-party identity providers (Facebook, Google, or
    Login with Amazon) or an Amazon Cognito user pool, and you can also
    choose to support unauthenticated access from your app. Cognito delivers
    a unique identifier for each user and acts as an OpenID token provider
    trusted by Security Token Service (STS) to access temporary,
    limited-privilege Amazon Web Services credentials.

    For a description of the authentication flow from the Amazon Cognito
    Developer Guide see [Authentication
    Flow](https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html).

    For more information see [Amazon Cognito Federated
    Identities](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html).
    """

    def __init__(
        self,
        config: AsyncCognitoIdentityConfig | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncCognitoIdentityClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        self._config = config
        self._plugins = plugins
        self._derive_lock = asyncio.Lock()
        self._setup_done = False
        self._closed = False
        self._retry_strategy_resolver = RetryStrategyResolver()
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> None:
        if not self._setup_done:
            async with self._derive_lock:
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncCognitoIdentityConfig.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    self._config = config

                    if self._config.aws_credentials_identity_resolver is None:
                        config_context = self._config.resolution_context()
                        config_file = None
                        profile_name = None
                        if config_context is not None:
                            config_file = await config_context.parsed_profiles()
                            if config_context.profile_source is ConfigSource.OVERRIDE:
                                profile_name = config_context.profile_name
                        self._config.aws_credentials_identity_resolver = (
                            await IdentityChain.create(
                                AWSCredentialsIdentity,
                                config_file=config_file,
                                profile_name=profile_name,
                                region_override=self._config.region,
                                http_client=cast(
                                    HTTPClient | None, self._config.transport
                                ),
                            )
                        )
                    self._setup_done = True

    async def close(self) -> None:
        """Close this client and any resources held by its transport."""
        if self._closed:
            return
        async with self._derive_lock:
            if self._closed:
                return
            self._closed = True
            if self._setup_done and self._config is not None:
                await close(self._config.transport)

    async def __aenter__(self) -> Self:
        if self._closed:
            raise RuntimeError("Cannot enter a client that has been closed.")
        return self

    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        await self.close()

    async def create_identity_pool(
        self, input: CreateIdentityPoolInput, plugins: list[Plugin] | None = None
    ) -> CreateIdentityPoolOutput:
        """
        Creates a new identity pool. The identity pool is a store of user
        identity information that is specific to your Amazon Web Services
        account. The keys for `SupportedLoginProviders` are as follows:

        - Facebook: `graph.facebook.com`

        - Google: `accounts.google.com`

        - Sign in With Apple: `appleid.apple.com`

        - Amazon: `www.amazon.com`

        - Twitter: `api.twitter.com`

        - Digits: `www.digits.com`

        Warning:
            If you don't provide a value for a parameter, Amazon Cognito sets it to
            its default value.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `CreateIdentityPoolInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateIdentityPoolOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_IDENTITY_POOL,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def delete_identities(
        self, input: DeleteIdentitiesInput, plugins: list[Plugin] | None = None
    ) -> DeleteIdentitiesOutput:
        """
        Deletes identities from an identity pool. You can specify a list of 1-60
        identities that you want to delete.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `DeleteIdentitiesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteIdentitiesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_IDENTITIES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def delete_identity_pool(
        self, input: DeleteIdentityPoolInput, plugins: list[Plugin] | None = None
    ) -> DeleteIdentityPoolOutput:
        """
        Deletes an identity pool. Once a pool is deleted, users will not be able
        to authenticate with the pool.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `DeleteIdentityPoolInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteIdentityPoolOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_IDENTITY_POOL,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def describe_identity(
        self, input: DescribeIdentityInput, plugins: list[Plugin] | None = None
    ) -> DescribeIdentityOutput:
        """
        Returns metadata related to the given identity, including when the
        identity was created and any associated linked logins.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `DescribeIdentityInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DescribeIdentityOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DESCRIBE_IDENTITY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def describe_identity_pool(
        self, input: DescribeIdentityPoolInput, plugins: list[Plugin] | None = None
    ) -> DescribeIdentityPoolOutput:
        """
        Gets details about a particular identity pool, including the pool name,
        ID description, creation date, and current number of users.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `DescribeIdentityPoolInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DescribeIdentityPoolOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DESCRIBE_IDENTITY_POOL,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_credentials_for_identity(
        self, input: GetCredentialsForIdentityInput, plugins: list[Plugin] | None = None
    ) -> GetCredentialsForIdentityOutput:
        """
        Returns credentials for the provided identity ID. Any provided logins
        will be validated against supported login providers. If the token is for
        `cognito-identity.amazonaws.com`, it will be passed through to Security
        Token Service with the appropriate role for the token.

        This is a public API. You do not need any credentials to call this API.

        Args:
            input:
                An instance of `GetCredentialsForIdentityInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetCredentialsForIdentityOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_CREDENTIALS_FOR_IDENTITY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_id(
        self, input: GetIdInput, plugins: list[Plugin] | None = None
    ) -> GetIdOutput:
        """
        Generates (or retrieves) IdentityID. Supplying multiple logins will
        create an implicit linked account.

        This is a public API. You do not need any credentials to call this API.

        Args:
            input:
                An instance of `GetIdInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetIdOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_ID,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_identity_pool_roles(
        self, input: GetIdentityPoolRolesInput, plugins: list[Plugin] | None = None
    ) -> GetIdentityPoolRolesOutput:
        """
        Gets the roles for an identity pool.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `GetIdentityPoolRolesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetIdentityPoolRolesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_IDENTITY_POOL_ROLES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_open_id_token(
        self, input: GetOpenIdTokenInput, plugins: list[Plugin] | None = None
    ) -> GetOpenIdTokenOutput:
        """
        Gets an OpenID token, using a known Cognito ID. This known Cognito ID is
        returned by GetId. You can optionally add additional logins for the
        identity. Supplying multiple logins creates an implicit link.

        The OpenID token is valid for 10 minutes.

        This is a public API. You do not need any credentials to call this API.

        Args:
            input:
                An instance of `GetOpenIdTokenInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetOpenIdTokenOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_OPEN_ID_TOKEN,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_open_id_token_for_developer_identity(
        self,
        input: GetOpenIdTokenForDeveloperIdentityInput,
        plugins: list[Plugin] | None = None,
    ) -> GetOpenIdTokenForDeveloperIdentityOutput:
        """
        Registers (or retrieves) a Cognito `IdentityId` and an OpenID Connect
        token for a user authenticated by your backend authentication process.
        Supplying multiple logins will create an implicit linked account. You
        can only specify one developer provider as part of the `Logins` map,
        which is linked to the identity pool. The developer provider is the
        \"domain\" by which Cognito will refer to your users.

        You can use `GetOpenIdTokenForDeveloperIdentity` to create a new
        identity and to link new logins (that is, user credentials issued by a
        public provider or developer provider) to an existing identity. When you
        want to create a new identity, the `IdentityId` should be null. When you
        want to associate a new login with an existing
        authenticated/unauthenticated identity, you can do so by providing the
        existing `IdentityId`. This API will create the identity in the
        specified `IdentityPoolId`.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `GetOpenIdTokenForDeveloperIdentityInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetOpenIdTokenForDeveloperIdentityOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_OPEN_ID_TOKEN_FOR_DEVELOPER_IDENTITY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_principal_tag_attribute_map(
        self,
        input: GetPrincipalTagAttributeMapInput,
        plugins: list[Plugin] | None = None,
    ) -> GetPrincipalTagAttributeMapOutput:
        """
        Use `GetPrincipalTagAttributeMap` to list all mappings between
        `PrincipalTags` and user attributes.

        Args:
            input:
                An instance of `GetPrincipalTagAttributeMapInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetPrincipalTagAttributeMapOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_PRINCIPAL_TAG_ATTRIBUTE_MAP,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_identities(
        self, input: ListIdentitiesInput, plugins: list[Plugin] | None = None
    ) -> ListIdentitiesOutput:
        """
        Lists the identities in an identity pool.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `ListIdentitiesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListIdentitiesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_IDENTITIES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_identity_pools(
        self, input: ListIdentityPoolsInput, plugins: list[Plugin] | None = None
    ) -> ListIdentityPoolsOutput:
        """
        Lists all of the Cognito identity pools registered for your account.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `ListIdentityPoolsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListIdentityPoolsOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_IDENTITY_POOLS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_tags_for_resource(
        self, input: ListTagsForResourceInput, plugins: list[Plugin] | None = None
    ) -> ListTagsForResourceOutput:
        """
        Lists the tags that are assigned to an Amazon Cognito identity pool.

        A tag is a label that you can apply to identity pools to categorize and
        manage them in different ways, such as by purpose, owner, environment,
        or other criteria.

        You can use this action up to 10 times per second, per account.

        Args:
            input:
                An instance of `ListTagsForResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListTagsForResourceOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_TAGS_FOR_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def lookup_developer_identity(
        self, input: LookupDeveloperIdentityInput, plugins: list[Plugin] | None = None
    ) -> LookupDeveloperIdentityOutput:
        """
        Retrieves the `IdentityID` associated with a `DeveloperUserIdentifier`
        or the list of `DeveloperUserIdentifier` values associated with an
        `IdentityId` for an existing identity. Either `IdentityID` or
        `DeveloperUserIdentifier` must not be null. If you supply only one of
        these values, the other value will be searched in the database and
        returned as a part of the response. If you supply both,
        `DeveloperUserIdentifier` will be matched against `IdentityID`. If the
        values are verified against the database, the response returns both
        values and is the same as the request. Otherwise, a
        `ResourceConflictException` is thrown.

        `LookupDeveloperIdentity` is intended for low-throughput control plane
        operations: for example, to enable customer service to locate an
        identity ID by username. If you are using it for higher-volume
        operations such as user authentication, your requests are likely to be
        throttled. GetOpenIdTokenForDeveloperIdentity is a better option for
        higher-volume operations for user authentication.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `LookupDeveloperIdentityInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `LookupDeveloperIdentityOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LOOKUP_DEVELOPER_IDENTITY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def merge_developer_identities(
        self, input: MergeDeveloperIdentitiesInput, plugins: list[Plugin] | None = None
    ) -> MergeDeveloperIdentitiesOutput:
        """
        Merges two users having different `IdentityId`s, existing in the same
        identity pool, and identified by the same developer provider. You can
        use this action to request that discrete users be merged and identified
        as a single user in the Cognito environment. Cognito associates the
        given source user (`SourceUserIdentifier`) with the `IdentityId` of the
        `DestinationUserIdentifier`. Only developer-authenticated users can be
        merged. If the users to be merged are associated with the same public
        provider, but as two different users, an exception will be thrown.

        The number of linked logins is limited to 20. So, the number of linked
        logins for the source user, `SourceUserIdentifier`, and the destination
        user, `DestinationUserIdentifier`, together should not be larger than
        20. Otherwise, an exception will be thrown.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `MergeDeveloperIdentitiesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `MergeDeveloperIdentitiesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=MERGE_DEVELOPER_IDENTITIES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def set_identity_pool_roles(
        self, input: SetIdentityPoolRolesInput, plugins: list[Plugin] | None = None
    ) -> SetIdentityPoolRolesOutput:
        """
        Sets the roles for an identity pool. These roles are used when making
        calls to GetCredentialsForIdentity action.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `SetIdentityPoolRolesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SetIdentityPoolRolesOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=SET_IDENTITY_POOL_ROLES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def set_principal_tag_attribute_map(
        self,
        input: SetPrincipalTagAttributeMapInput,
        plugins: list[Plugin] | None = None,
    ) -> SetPrincipalTagAttributeMapOutput:
        """
        You can use this operation to use default (username and clientID)
        attribute or custom attribute mappings.

        Args:
            input:
                An instance of `SetPrincipalTagAttributeMapInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SetPrincipalTagAttributeMapOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=SET_PRINCIPAL_TAG_ATTRIBUTE_MAP,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def tag_resource(
        self, input: TagResourceInput, plugins: list[Plugin] | None = None
    ) -> TagResourceOutput:
        """
        Assigns a set of tags to the specified Amazon Cognito identity pool. A
        tag is a label that you can use to categorize and manage identity pools
        in different ways, such as by purpose, owner, environment, or other
        criteria.

        Each tag consists of a key and value, both of which you define. A key is
        a general category for more specific values. For example, if you have
        two versions of an identity pool, one for testing and another for
        production, you might assign an `Environment` tag key to both identity
        pools. The value of this key might be `Test` for one identity pool and
        `Production` for the other.

        Tags are useful for cost tracking and access control. You can activate
        your tags so that they appear on the Billing and Cost Management
        console, where you can track the costs associated with your identity
        pools. In an IAM policy, you can constrain permissions for identity
        pools based on specific tags or tag values.

        You can use this action up to 5 times per second, per account. An
        identity pool can have as many as 50 tags.

        Args:
            input:
                An instance of `TagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `TagResourceOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=TAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def unlink_developer_identity(
        self, input: UnlinkDeveloperIdentityInput, plugins: list[Plugin] | None = None
    ) -> UnlinkDeveloperIdentityOutput:
        """
        Unlinks a `DeveloperUserIdentifier` from an existing identity. Unlinked
        developer users will be considered new identities next time they are
        seen. If, for a given Cognito identity, you remove all federated
        identities as well as the developer user identifier, the Cognito
        identity becomes inaccessible.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `UnlinkDeveloperIdentityInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UnlinkDeveloperIdentityOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UNLINK_DEVELOPER_IDENTITY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def unlink_identity(
        self, input: UnlinkIdentityInput, plugins: list[Plugin] | None = None
    ) -> UnlinkIdentityOutput:
        """
        Unlinks a federated identity from an existing account. Unlinked logins
        will be considered new identities next time they are seen. Removing the
        last linked login will make this identity inaccessible.

        This is a public API. You do not need any credentials to call this API.

        Args:
            input:
                An instance of `UnlinkIdentityInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UnlinkIdentityOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UNLINK_IDENTITY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def untag_resource(
        self, input: UntagResourceInput, plugins: list[Plugin] | None = None
    ) -> UntagResourceOutput:
        """
        Removes the specified tags from the specified Amazon Cognito identity
        pool. You can use this action up to 5 times per second, per account

        Args:
            input:
                An instance of `UntagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UntagResourceOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UNTAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def update_identity_pool(
        self, input: UpdateIdentityPoolInput, plugins: list[Plugin] | None = None
    ) -> UpdateIdentityPoolOutput:
        """
        Updates the configuration of an identity pool.

        Warning:
            If you don't provide a value for a parameter, Amazon Cognito sets it to
            its default value.

        You must use Amazon Web Services developer credentials to call this
        operation.

        Args:
            input:
                An instance of `UpdateIdentityPoolInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UpdateIdentityPoolOutput`.
        """
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )

        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        await self._ensure_setup()
        assert self._config is not None
        if operation_plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(self._config)
            for plugin in operation_plugins:
                plugin(config)
        else:
            config = self._config
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UPDATE_IDENTITY_POOL,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)
