# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import AwsJson11ClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient

from ._private.schemas import CLOUD_TRAIL_20131101 as _SCHEMA_CLOUD_TRAIL_20131101
from .auth import HTTPAuthSchemeResolver
from .models import (
    AddTagsInput,
    AddTagsOutput,
    CancelQueryInput,
    CancelQueryOutput,
    CreateChannelInput,
    CreateChannelOutput,
    CreateDashboardInput,
    CreateDashboardOutput,
    CreateEventDataStoreInput,
    CreateEventDataStoreOutput,
    CreateTrailInput,
    CreateTrailOutput,
    DeleteChannelInput,
    DeleteChannelOutput,
    DeleteDashboardInput,
    DeleteDashboardOutput,
    DeleteEventDataStoreInput,
    DeleteEventDataStoreOutput,
    DeleteResourcePolicyInput,
    DeleteResourcePolicyOutput,
    DeleteTrailInput,
    DeleteTrailOutput,
    DeregisterOrganizationDelegatedAdminInput,
    DeregisterOrganizationDelegatedAdminOutput,
    DescribeQueryInput,
    DescribeQueryOutput,
    DescribeTrailsInput,
    DescribeTrailsOutput,
    DisableFederationInput,
    DisableFederationOutput,
    EnableFederationInput,
    EnableFederationOutput,
    GenerateQueryInput,
    GenerateQueryOutput,
    GetChannelInput,
    GetChannelOutput,
    GetDashboardInput,
    GetDashboardOutput,
    GetEventConfigurationInput,
    GetEventConfigurationOutput,
    GetEventDataStoreInput,
    GetEventDataStoreOutput,
    GetEventSelectorsInput,
    GetEventSelectorsOutput,
    GetImportInput,
    GetImportOutput,
    GetInsightSelectorsInput,
    GetInsightSelectorsOutput,
    GetQueryResultsInput,
    GetQueryResultsOutput,
    GetResourcePolicyInput,
    GetResourcePolicyOutput,
    GetTrailInput,
    GetTrailOutput,
    GetTrailStatusInput,
    GetTrailStatusOutput,
    ListChannelsInput,
    ListChannelsOutput,
    ListDashboardsInput,
    ListDashboardsOutput,
    ListEventDataStoresInput,
    ListEventDataStoresOutput,
    ListImportFailuresInput,
    ListImportFailuresOutput,
    ListImportsInput,
    ListImportsOutput,
    ListInsightsDataInput,
    ListInsightsDataOutput,
    ListInsightsMetricDataInput,
    ListInsightsMetricDataOutput,
    ListPublicKeysInput,
    ListPublicKeysOutput,
    ListQueriesInput,
    ListQueriesOutput,
    ListTagsInput,
    ListTagsOutput,
    ListTrailsInput,
    ListTrailsOutput,
    LookupEventsInput,
    LookupEventsOutput,
    PutEventConfigurationInput,
    PutEventConfigurationOutput,
    PutEventSelectorsInput,
    PutEventSelectorsOutput,
    PutInsightSelectorsInput,
    PutInsightSelectorsOutput,
    PutResourcePolicyInput,
    PutResourcePolicyOutput,
    RegisterOrganizationDelegatedAdminInput,
    RegisterOrganizationDelegatedAdminOutput,
    RemoveTagsInput,
    RemoveTagsOutput,
    RestoreEventDataStoreInput,
    RestoreEventDataStoreOutput,
    SearchSampleQueriesInput,
    SearchSampleQueriesOutput,
    StartDashboardRefreshInput,
    StartDashboardRefreshOutput,
    StartEventDataStoreIngestionInput,
    StartEventDataStoreIngestionOutput,
    StartImportInput,
    StartImportOutput,
    StartLoggingInput,
    StartLoggingOutput,
    StartQueryInput,
    StartQueryOutput,
    StopEventDataStoreIngestionInput,
    StopEventDataStoreIngestionOutput,
    StopImportInput,
    StopImportOutput,
    StopLoggingInput,
    StopLoggingOutput,
    UpdateChannelInput,
    UpdateChannelOutput,
    UpdateDashboardInput,
    UpdateDashboardOutput,
    UpdateEventDataStoreInput,
    UpdateEventDataStoreOutput,
    UpdateTrailInput,
    UpdateTrailOutput,
)


_ServiceInterceptor = Union[
    Interceptor[AddTagsInput, AddTagsOutput, Any, Any],
    Interceptor[CancelQueryInput, CancelQueryOutput, Any, Any],
    Interceptor[CreateChannelInput, CreateChannelOutput, Any, Any],
    Interceptor[CreateDashboardInput, CreateDashboardOutput, Any, Any],
    Interceptor[CreateEventDataStoreInput, CreateEventDataStoreOutput, Any, Any],
    Interceptor[CreateTrailInput, CreateTrailOutput, Any, Any],
    Interceptor[DeleteChannelInput, DeleteChannelOutput, Any, Any],
    Interceptor[DeleteDashboardInput, DeleteDashboardOutput, Any, Any],
    Interceptor[DeleteEventDataStoreInput, DeleteEventDataStoreOutput, Any, Any],
    Interceptor[DeleteResourcePolicyInput, DeleteResourcePolicyOutput, Any, Any],
    Interceptor[DeleteTrailInput, DeleteTrailOutput, Any, Any],
    Interceptor[
        DeregisterOrganizationDelegatedAdminInput,
        DeregisterOrganizationDelegatedAdminOutput,
        Any,
        Any,
    ],
    Interceptor[DescribeQueryInput, DescribeQueryOutput, Any, Any],
    Interceptor[DescribeTrailsInput, DescribeTrailsOutput, Any, Any],
    Interceptor[DisableFederationInput, DisableFederationOutput, Any, Any],
    Interceptor[EnableFederationInput, EnableFederationOutput, Any, Any],
    Interceptor[GenerateQueryInput, GenerateQueryOutput, Any, Any],
    Interceptor[GetChannelInput, GetChannelOutput, Any, Any],
    Interceptor[GetDashboardInput, GetDashboardOutput, Any, Any],
    Interceptor[GetEventConfigurationInput, GetEventConfigurationOutput, Any, Any],
    Interceptor[GetEventDataStoreInput, GetEventDataStoreOutput, Any, Any],
    Interceptor[GetEventSelectorsInput, GetEventSelectorsOutput, Any, Any],
    Interceptor[GetImportInput, GetImportOutput, Any, Any],
    Interceptor[GetInsightSelectorsInput, GetInsightSelectorsOutput, Any, Any],
    Interceptor[GetQueryResultsInput, GetQueryResultsOutput, Any, Any],
    Interceptor[GetResourcePolicyInput, GetResourcePolicyOutput, Any, Any],
    Interceptor[GetTrailInput, GetTrailOutput, Any, Any],
    Interceptor[GetTrailStatusInput, GetTrailStatusOutput, Any, Any],
    Interceptor[ListChannelsInput, ListChannelsOutput, Any, Any],
    Interceptor[ListDashboardsInput, ListDashboardsOutput, Any, Any],
    Interceptor[ListEventDataStoresInput, ListEventDataStoresOutput, Any, Any],
    Interceptor[ListImportFailuresInput, ListImportFailuresOutput, Any, Any],
    Interceptor[ListImportsInput, ListImportsOutput, Any, Any],
    Interceptor[ListInsightsDataInput, ListInsightsDataOutput, Any, Any],
    Interceptor[ListInsightsMetricDataInput, ListInsightsMetricDataOutput, Any, Any],
    Interceptor[ListPublicKeysInput, ListPublicKeysOutput, Any, Any],
    Interceptor[ListQueriesInput, ListQueriesOutput, Any, Any],
    Interceptor[ListTagsInput, ListTagsOutput, Any, Any],
    Interceptor[ListTrailsInput, ListTrailsOutput, Any, Any],
    Interceptor[LookupEventsInput, LookupEventsOutput, Any, Any],
    Interceptor[PutEventConfigurationInput, PutEventConfigurationOutput, Any, Any],
    Interceptor[PutEventSelectorsInput, PutEventSelectorsOutput, Any, Any],
    Interceptor[PutInsightSelectorsInput, PutInsightSelectorsOutput, Any, Any],
    Interceptor[PutResourcePolicyInput, PutResourcePolicyOutput, Any, Any],
    Interceptor[
        RegisterOrganizationDelegatedAdminInput,
        RegisterOrganizationDelegatedAdminOutput,
        Any,
        Any,
    ],
    Interceptor[RemoveTagsInput, RemoveTagsOutput, Any, Any],
    Interceptor[RestoreEventDataStoreInput, RestoreEventDataStoreOutput, Any, Any],
    Interceptor[SearchSampleQueriesInput, SearchSampleQueriesOutput, Any, Any],
    Interceptor[StartDashboardRefreshInput, StartDashboardRefreshOutput, Any, Any],
    Interceptor[
        StartEventDataStoreIngestionInput, StartEventDataStoreIngestionOutput, Any, Any
    ],
    Interceptor[StartImportInput, StartImportOutput, Any, Any],
    Interceptor[StartLoggingInput, StartLoggingOutput, Any, Any],
    Interceptor[StartQueryInput, StartQueryOutput, Any, Any],
    Interceptor[
        StopEventDataStoreIngestionInput, StopEventDataStoreIngestionOutput, Any, Any
    ],
    Interceptor[StopImportInput, StopImportOutput, Any, Any],
    Interceptor[StopLoggingInput, StopLoggingOutput, Any, Any],
    Interceptor[UpdateChannelInput, UpdateChannelOutput, Any, Any],
    Interceptor[UpdateDashboardInput, UpdateDashboardOutput, Any, Any],
    Interceptor[UpdateEventDataStoreInput, UpdateEventDataStoreOutput, Any, Any],
    Interceptor[UpdateTrailInput, UpdateTrailOutput, Any, Any],
]


class _AsyncCloudTrailConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: ClientProtocol[Any, Any] | None
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: HTTPAuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncCloudTrailConfig(AsyncAwsConfig):
    """CloudTrail configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """The protocol to serialize and deserialize requests with."""

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: HTTPAuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(
            default=None, resolver=EndpointUriResolver("cloudtrail")
        ),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="cloudtrail"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: AwsJson11ClientProtocol(
                _SCHEMA_CLOUD_TRAIL_20131101
            )
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="cloudtrail")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AIOHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncCloudTrailConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncCloudTrailConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
