# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass, field
from typing import Any, Callable, ClassVar, Self, TypeAlias, Union, Unpack

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.config import AwsConfigOverrides, FileSystem
from smithy_aws_core.config.aws_config import AsyncAwsConfig
from smithy_aws_core.config.resolvers import EndpointUriResolver
from smithy_aws_core.config.types import FieldSpec
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.interceptors import Interceptor
from smithy_core.shapes import ShapeID
from smithy_http.aio.crt import AWSCRTHTTPClient

from ._private.schemas import (
    AMAZON_BEDROCK_AGENT_CORE as _SCHEMA_AMAZON_BEDROCK_AGENT_CORE,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    BatchCreateMemoryRecordsInput,
    BatchCreateMemoryRecordsOutput,
    BatchDeleteMemoryRecordsInput,
    BatchDeleteMemoryRecordsOutput,
    BatchUpdateMemoryRecordsInput,
    BatchUpdateMemoryRecordsOutput,
    CompleteResourceTokenAuthInput,
    CompleteResourceTokenAuthOutput,
    CreateABTestInput,
    CreateABTestOutput,
    CreateEventInput,
    CreateEventOutput,
    CreatePaymentInstrumentInput,
    CreatePaymentInstrumentOutput,
    CreatePaymentSessionInput,
    CreatePaymentSessionOutput,
    DeleteABTestInput,
    DeleteABTestOutput,
    DeleteBatchEvaluationInput,
    DeleteBatchEvaluationOutput,
    DeleteCapacityProviderSessionInput,
    DeleteCapacityProviderSessionOutput,
    DeleteEventInput,
    DeleteEventOutput,
    DeleteMemoryRecordInput,
    DeleteMemoryRecordOutput,
    DeletePaymentInstrumentInput,
    DeletePaymentInstrumentOutput,
    DeletePaymentSessionInput,
    DeletePaymentSessionOutput,
    DeleteRecommendationInput,
    DeleteRecommendationOutput,
    EvaluateInput,
    EvaluateOutput,
    GetABTestInput,
    GetABTestOutput,
    GetAgentCardInput,
    GetAgentCardOutput,
    GetBatchEvaluationInput,
    GetBatchEvaluationOutput,
    GetBrowserSessionInput,
    GetBrowserSessionOutput,
    GetCodeInterpreterSessionInput,
    GetCodeInterpreterSessionOutput,
    GetEventInput,
    GetEventOutput,
    GetMemoryRecordInput,
    GetMemoryRecordOutput,
    GetPaymentInstrumentBalanceInput,
    GetPaymentInstrumentBalanceOutput,
    GetPaymentInstrumentInput,
    GetPaymentInstrumentOutput,
    GetPaymentSessionInput,
    GetPaymentSessionOutput,
    GetRecommendationInput,
    GetRecommendationOutput,
    GetResourceApiKeyInput,
    GetResourceApiKeyOutput,
    GetResourceOauth2TokenInput,
    GetResourceOauth2TokenOutput,
    GetResourcePaymentTokenInput,
    GetResourcePaymentTokenOutput,
    GetWorkloadAccessTokenForJWTInput,
    GetWorkloadAccessTokenForJWTOutput,
    GetWorkloadAccessTokenForUserIdInput,
    GetWorkloadAccessTokenForUserIdOutput,
    GetWorkloadAccessTokenInput,
    GetWorkloadAccessTokenOutput,
    InvokeAgentRuntimeCommandInput,
    InvokeAgentRuntimeCommandOutput,
    InvokeAgentRuntimeInput,
    InvokeAgentRuntimeOutput,
    InvokeBrowserInput,
    InvokeBrowserOutput,
    InvokeCodeInterpreterInput,
    InvokeCodeInterpreterOutput,
    InvokeHarnessInput,
    InvokeHarnessOutput,
    ListABTestsInput,
    ListABTestsOutput,
    ListActorsInput,
    ListActorsOutput,
    ListBatchEvaluationsInput,
    ListBatchEvaluationsOutput,
    ListBrowserSessionsInput,
    ListBrowserSessionsOutput,
    ListCodeInterpreterSessionsInput,
    ListCodeInterpreterSessionsOutput,
    ListEventsInput,
    ListEventsOutput,
    ListMemoryExtractionJobsInput,
    ListMemoryExtractionJobsOutput,
    ListMemoryRecordsInput,
    ListMemoryRecordsOutput,
    ListPaymentInstrumentsInput,
    ListPaymentInstrumentsOutput,
    ListPaymentSessionsInput,
    ListPaymentSessionsOutput,
    ListRecommendationsInput,
    ListRecommendationsOutput,
    ListSessionsInput,
    ListSessionsOutput,
    ProcessPaymentInput,
    ProcessPaymentOutput,
    RetrieveMemoryRecordsInput,
    RetrieveMemoryRecordsOutput,
    SaveBrowserSessionProfileInput,
    SaveBrowserSessionProfileOutput,
    SearchRegistryRecordsInput,
    SearchRegistryRecordsOutput,
    StartBatchEvaluationInput,
    StartBatchEvaluationOutput,
    StartBrowserSessionInput,
    StartBrowserSessionOutput,
    StartCodeInterpreterSessionInput,
    StartCodeInterpreterSessionOutput,
    StartMemoryExtractionJobInput,
    StartMemoryExtractionJobOutput,
    StartRecommendationInput,
    StartRecommendationOutput,
    StopBatchEvaluationInput,
    StopBatchEvaluationOutput,
    StopBrowserSessionInput,
    StopBrowserSessionOutput,
    StopCodeInterpreterSessionInput,
    StopCodeInterpreterSessionOutput,
    StopRuntimeSessionInput,
    StopRuntimeSessionOutput,
    UpdateABTestInput,
    UpdateABTestOutput,
    UpdateBrowserStreamInput,
    UpdateBrowserStreamOutput,
)


_ServiceInterceptor = Union[
    Interceptor[
        BatchCreateMemoryRecordsInput, BatchCreateMemoryRecordsOutput, Any, Any
    ],
    Interceptor[
        BatchDeleteMemoryRecordsInput, BatchDeleteMemoryRecordsOutput, Any, Any
    ],
    Interceptor[
        BatchUpdateMemoryRecordsInput, BatchUpdateMemoryRecordsOutput, Any, Any
    ],
    Interceptor[
        CompleteResourceTokenAuthInput, CompleteResourceTokenAuthOutput, Any, Any
    ],
    Interceptor[CreateABTestInput, CreateABTestOutput, Any, Any],
    Interceptor[CreateEventInput, CreateEventOutput, Any, Any],
    Interceptor[CreatePaymentInstrumentInput, CreatePaymentInstrumentOutput, Any, Any],
    Interceptor[CreatePaymentSessionInput, CreatePaymentSessionOutput, Any, Any],
    Interceptor[DeleteABTestInput, DeleteABTestOutput, Any, Any],
    Interceptor[DeleteBatchEvaluationInput, DeleteBatchEvaluationOutput, Any, Any],
    Interceptor[
        DeleteCapacityProviderSessionInput,
        DeleteCapacityProviderSessionOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteEventInput, DeleteEventOutput, Any, Any],
    Interceptor[DeleteMemoryRecordInput, DeleteMemoryRecordOutput, Any, Any],
    Interceptor[DeletePaymentInstrumentInput, DeletePaymentInstrumentOutput, Any, Any],
    Interceptor[DeletePaymentSessionInput, DeletePaymentSessionOutput, Any, Any],
    Interceptor[DeleteRecommendationInput, DeleteRecommendationOutput, Any, Any],
    Interceptor[EvaluateInput, EvaluateOutput, Any, Any],
    Interceptor[GetABTestInput, GetABTestOutput, Any, Any],
    Interceptor[GetAgentCardInput, GetAgentCardOutput, Any, Any],
    Interceptor[GetBatchEvaluationInput, GetBatchEvaluationOutput, Any, Any],
    Interceptor[GetBrowserSessionInput, GetBrowserSessionOutput, Any, Any],
    Interceptor[
        GetCodeInterpreterSessionInput, GetCodeInterpreterSessionOutput, Any, Any
    ],
    Interceptor[GetEventInput, GetEventOutput, Any, Any],
    Interceptor[GetMemoryRecordInput, GetMemoryRecordOutput, Any, Any],
    Interceptor[GetPaymentInstrumentInput, GetPaymentInstrumentOutput, Any, Any],
    Interceptor[
        GetPaymentInstrumentBalanceInput, GetPaymentInstrumentBalanceOutput, Any, Any
    ],
    Interceptor[GetPaymentSessionInput, GetPaymentSessionOutput, Any, Any],
    Interceptor[GetRecommendationInput, GetRecommendationOutput, Any, Any],
    Interceptor[GetResourceApiKeyInput, GetResourceApiKeyOutput, Any, Any],
    Interceptor[GetResourceOauth2TokenInput, GetResourceOauth2TokenOutput, Any, Any],
    Interceptor[GetResourcePaymentTokenInput, GetResourcePaymentTokenOutput, Any, Any],
    Interceptor[GetWorkloadAccessTokenInput, GetWorkloadAccessTokenOutput, Any, Any],
    Interceptor[
        GetWorkloadAccessTokenForJWTInput, GetWorkloadAccessTokenForJWTOutput, Any, Any
    ],
    Interceptor[
        GetWorkloadAccessTokenForUserIdInput,
        GetWorkloadAccessTokenForUserIdOutput,
        Any,
        Any,
    ],
    Interceptor[InvokeAgentRuntimeInput, InvokeAgentRuntimeOutput, Any, Any],
    Interceptor[
        InvokeAgentRuntimeCommandInput, InvokeAgentRuntimeCommandOutput, Any, Any
    ],
    Interceptor[InvokeBrowserInput, InvokeBrowserOutput, Any, Any],
    Interceptor[InvokeCodeInterpreterInput, InvokeCodeInterpreterOutput, Any, Any],
    Interceptor[InvokeHarnessInput, InvokeHarnessOutput, Any, Any],
    Interceptor[ListABTestsInput, ListABTestsOutput, Any, Any],
    Interceptor[ListActorsInput, ListActorsOutput, Any, Any],
    Interceptor[ListBatchEvaluationsInput, ListBatchEvaluationsOutput, Any, Any],
    Interceptor[ListBrowserSessionsInput, ListBrowserSessionsOutput, Any, Any],
    Interceptor[
        ListCodeInterpreterSessionsInput, ListCodeInterpreterSessionsOutput, Any, Any
    ],
    Interceptor[ListEventsInput, ListEventsOutput, Any, Any],
    Interceptor[
        ListMemoryExtractionJobsInput, ListMemoryExtractionJobsOutput, Any, Any
    ],
    Interceptor[ListMemoryRecordsInput, ListMemoryRecordsOutput, Any, Any],
    Interceptor[ListPaymentInstrumentsInput, ListPaymentInstrumentsOutput, Any, Any],
    Interceptor[ListPaymentSessionsInput, ListPaymentSessionsOutput, Any, Any],
    Interceptor[ListRecommendationsInput, ListRecommendationsOutput, Any, Any],
    Interceptor[ListSessionsInput, ListSessionsOutput, Any, Any],
    Interceptor[ProcessPaymentInput, ProcessPaymentOutput, Any, Any],
    Interceptor[RetrieveMemoryRecordsInput, RetrieveMemoryRecordsOutput, Any, Any],
    Interceptor[
        SaveBrowserSessionProfileInput, SaveBrowserSessionProfileOutput, Any, Any
    ],
    Interceptor[SearchRegistryRecordsInput, SearchRegistryRecordsOutput, Any, Any],
    Interceptor[StartBatchEvaluationInput, StartBatchEvaluationOutput, Any, Any],
    Interceptor[StartBrowserSessionInput, StartBrowserSessionOutput, Any, Any],
    Interceptor[
        StartCodeInterpreterSessionInput, StartCodeInterpreterSessionOutput, Any, Any
    ],
    Interceptor[
        StartMemoryExtractionJobInput, StartMemoryExtractionJobOutput, Any, Any
    ],
    Interceptor[StartRecommendationInput, StartRecommendationOutput, Any, Any],
    Interceptor[StopBatchEvaluationInput, StopBatchEvaluationOutput, Any, Any],
    Interceptor[StopBrowserSessionInput, StopBrowserSessionOutput, Any, Any],
    Interceptor[
        StopCodeInterpreterSessionInput, StopCodeInterpreterSessionOutput, Any, Any
    ],
    Interceptor[StopRuntimeSessionInput, StopRuntimeSessionOutput, Any, Any],
    Interceptor[UpdateABTestInput, UpdateABTestOutput, Any, Any],
    Interceptor[UpdateBrowserStreamInput, UpdateBrowserStreamOutput, Any, Any],
]


class _AsyncBedrockAgentCoreConfigOverrides(AwsConfigOverrides, total=False):
    endpoint_resolver: EndpointResolver | None
    protocol: ClientProtocol[Any, Any] | None
    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None
    auth_scheme_resolver: HTTPAuthSchemeResolver | None


@dataclass(kw_only=True, repr=False, init=False)
class AsyncBedrockAgentCoreConfig(AsyncAwsConfig):
    """Bedrock AgentCore configuration (async-resolved)."""

    endpoint_resolver: EndpointResolver | None = None
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    protocol: ClientProtocol[Any, Any] | None = None
    """The protocol to serialize and deserialize requests with."""

    interceptors: list[_ServiceInterceptor] = field(default_factory=lambda: [])
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None
    """A map of auth scheme ids to auth schemes."""

    auth_scheme_resolver: HTTPAuthSchemeResolver | None = None
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    ) = None
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    region: str | None = None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    aws_access_key_id: str | None = None
    """The identifier for a secret access key."""

    aws_secret_access_key: str | None = None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None = None
    """The session token used with temporary AWS credentials."""

    user_agent_extra: str | None = None
    """Additional suffix to be added to the User-Agent header."""

    sdk_ua_app_id: str | None = None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    _FIELDS: ClassVar[dict[str, FieldSpec]] = {
        "aws_credentials_identity_resolver": FieldSpec(default=None),
        "region": FieldSpec(default=None),
        "aws_access_key_id": FieldSpec(default=None),
        "aws_secret_access_key": FieldSpec(default=None),
        "aws_session_token": FieldSpec(default=None),
        "user_agent_extra": FieldSpec(default=None),
        "sdk_ua_app_id": FieldSpec(default=None),
        **AsyncAwsConfig._FIELDS,
        "endpoint_uri": FieldSpec(
            default=None, resolver=EndpointUriResolver("bedrock_agentcore")
        ),
        "endpoint_resolver": FieldSpec(
            default_factory=lambda: StandardRegionalEndpointsResolver(
                endpoint_prefix="bedrock-agentcore"
            )
        ),
        "protocol": FieldSpec(
            default_factory=lambda: RestJsonClientProtocol(
                _SCHEMA_AMAZON_BEDROCK_AGENT_CORE
            )
        ),
        "auth_schemes": FieldSpec(
            default_factory=lambda: {
                ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="bedrock-agentcore")
            }
        ),
        "auth_scheme_resolver": FieldSpec(default_factory=HTTPAuthSchemeResolver),
        "transport": FieldSpec(default_factory=lambda: AWSCRTHTTPClient()),
    }

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Set an auth scheme implementation using its scheme ID. :param scheme:
        The auth scheme to add or replace.
        """
        auth_schemes = dict(self.auth_schemes or {})
        auth_schemes[scheme.scheme_id] = scheme
        self.auth_schemes = auth_schemes

    @classmethod
    async def resolve(  # pyright: ignore[reportIncompatibleMethodOverride]
        cls,
        *,
        profile: str | None = None,
        fs: FileSystem | None = None,
        config_file_path: str | None = None,
        credentials_file_path: str | None = None,
        **overrides: Unpack[_AsyncBedrockAgentCoreConfigOverrides],
    ) -> Self:
        """
        Resolve config from environment, config files, defaults, and explicit
        overrides.
        """
        return await cls._resolve(
            profile=profile,
            fs=fs,
            config_file_path=config_file_path,
            credentials_file_path=credentials_file_path,
            overrides=overrides,
        )


Plugin: TypeAlias = Callable[[AsyncBedrockAgentCoreConfig], None]
"""
A callable that customizes a client configuration. Service-level plugins
are applied once to the base configuration inherited by every operation.
Operation-level plugins apply only to a single operation invocation.
"""
